# CELL 1: Setup & Dependencies

In [ ]:
import pandas as pd

In [ ]:
import json

In [ ]:
# Mount Drive and target correct folder
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
DATA_PATH = '/content/drive/MyDrive/Startups_Recognize/Startups_Dataset_Merge.csv'
df = pd.read_csv(DATA_PATH)

In [ ]:
%cd "/content/drive/MyDrive/Startups_Recognize"

/content/drive/MyDrive/Startups_Recognize

In [ ]:
# Load dataset and handle duplicates / NaNs
#df = df.dropna().reset_index(drop=True)

In [ ]:
df.head()

,name,motto,description,genres,url
0,OutboundGateway,Route traffic securely with TLS passthrough an...,OutboundGateway provides a secure HTTPS (CONNE...,"Internet Service Providers, Enterprise Securit...",https://betalist.com/startups/outboundgateway
1,Flux Plugins,"Speed up WordPress with AI-powered image, SEO,...",Flux Plugins provides a suite of WordPress plu...,"Blogging Platforms, Optimization, Performance ...",https://betalist.com/startups/flux-plugins
2,Wafaa.io BOOSTED,Create digital contracts in minutes,Wafaa is your new one-stop shop for digital co...,"SaaS, B2B, Freelancers",https://betalist.com/startups/wafaa-io
3,Vaulternal,Store and automate file access with secure fil...,"Vaulternal offers encrypted, decentralized fil...","Lifestyle, File Sharing, Storage, Accessibilit...",https://betalist.com/startups/vaulternal
4,PUBVOICE,Turn your articles into audio and boost reader...,PUBVOICE converts your articles into high-qual...,"Speech Recognition, Publishing, Audio, Accessi...",https://betalist.com/startups/pubvoice

In [ ]:
df.shape

(21408, 5)

In [ ]:
df.isnull().sum()

name           0
motto          6
description    0
genres         0
url            0
dtype: int64

In [ ]:
df.dropna(inplace=True, axis=0)

In [ ]:
df.shape

(21402, 5)

In [ ]:
df.isnull().sum()

name           0
motto          0
description    0
genres         0
url            0
dtype: int64

In [ ]:
df.rename(columns={"genres": "topics"}, inplace=True)

In [ ]:
df.head()

,name,motto,description,topics,url
0,OutboundGateway,Route traffic securely with TLS passthrough an...,OutboundGateway provides a secure HTTPS (CONNE...,"Internet Service Providers, Enterprise Securit...",https://betalist.com/startups/outboundgateway
1,Flux Plugins,"Speed up WordPress with AI-powered image, SEO,...",Flux Plugins provides a suite of WordPress plu...,"Blogging Platforms, Optimization, Performance ...",https://betalist.com/startups/flux-plugins
2,Wafaa.io BOOSTED,Create digital contracts in minutes,Wafaa is your new one-stop shop for digital co...,"SaaS, B2B, Freelancers",https://betalist.com/startups/wafaa-io
3,Vaulternal,Store and automate file access with secure fil...,"Vaulternal offers encrypted, decentralized fil...","Lifestyle, File Sharing, Storage, Accessibilit...",https://betalist.com/startups/vaulternal
4,PUBVOICE,Turn your articles into audio and boost reader...,PUBVOICE converts your articles into high-qual...,"Speech Recognition, Publishing, Audio, Accessi...",https://betalist.com/startups/pubvoice

In [ ]:
topics_list = df.topics.to_list()

In [ ]:
topics = [topic.strip() for topics in topics_list for topic in topics.split(",")]

In [ ]:
topics[:5]

['Internet Service Providers',
 'Enterprise Security',
 'Networking',
 'Accessibility',
 'Data Privacy']

In [ ]:
topic_count = {}
for topic in topics:
  if topic in topic_count.keys():
    topic_count[topic] += 1
  else:
    topic_count[topic] = 1

In [ ]:
print(f"Number of topics: {len(topic_count)}")
print(dict(sorted(topic_count.items(), key=(lambda x: x[1]), reverse=True)))

Number of topics: 811
{'SaaS': 13137, 'Startups': 7295, 'Web Tools': 5870, 'Developer Tools': 5698, 'Productivity Software': 4966, 'Web Development': 4178, 'Business Productivity': 3805, 'Small and Medium Businesses': 2205, 'Sales and Marketing': 1824, 'Web Design': 1511, 'Artificial Intelligence': 1399, 'Analytics': 1320, 'Apps': 1268, 'B2B': 1118, 'Collaboration': 1093, 'Internet Marketing': 1049, 'Mobile': 888, 'Developer APIs': 881, 'E-Commerce': 848, 'Social Media': 843, 'Development Platforms': 820, 'Design': 804, 'Software': 790, 'Sales Automation': 748, 'Education': 709, 'AI Tools': 681, 'Project Management': 638, 'Technology': 620, 'Business Services': 525, 'Marketing Automation': 494, 'Enterprise Software': 478, 'CRM': 448, 'AI Chat': 443, 'No Code': 409, 'Customer Support Tools': 400, 'User Experience Design': 399, 'Email': 374, 'Web CMS': 372, 'Recruiting': 356, 'Browser Extensions': 343, 'Human Resources': 343, 'Email Marketing': 333, 'Social Media Marketing': 320, 'Chat': 301, 'Freelancers': 285, 'Designers': 285, 'Content Creators': 275, 'Product Design': 274, 'Finance Technology': 268, 'Web Hosting': 266, 'Lead Generation': 255, 'iOS': 255, 'SEO': 238, 'New Product Development': 237, 'Finance': 236, 'Databases': 233, 'Machine Learning': 229, 'Business Analytics': 227, 'Customer Service': 226, 'AI Image Creation': 217, 'Data Integration': 216, 'Tracking': 215, 'Communities': 213, 'Video': 212, 'Remote Work': 201, 'Brand Marketing': 197, 'User Testing': 197, 'Business Intelligence': 191, 'Legal': 186, 'Task Management': 184, 'Marketplaces': 180, 'Document Management': 169, 'Data Visualization': 166, 'Private Social Networking': 165, 'Application Performance Monitoring': 162, 'Cryptocurrencies': 160, 'Business Development': 157, 'Mobile Social': 157, 'Email Newsletters': 155, 'Market Research': 154, 'Blockchain': 153, 'Blogging Platforms': 152, 'Feedback Tools': 152, 'Entrepreneur': 151, 'Domains': 148, 'Human Resource Automation': 147, 'Security': 145, 'Health and Wellness': 139, 'Presentations': 137, 'Content': 136, 'Cloud Data Services': 133, 'Bots': 133, 'Graphics': 130, 'Messaging': 128, 'AI Marketing': 124, 'Meeting Software': 124, 'Lead Management': 119, 'Career Planning': 117, 'Video Editing': 115, 'Cloud Computing': 113, 'Cloud Infrastructure': 112, 'Information Technology': 109, 'Privacy': 108, 'Search Marketing': 105, 'Career Management': 105, 'Knowledge Management': 103, 'Cyber Security': 101, 'AI Assistant': 101, 'Performance Marketing': 100, 'Lifestyle': 100, 'Payments': 100, 'Contact Management': 97, 'Test and Measurement': 97, 'Accounting': 97, 'Application Platforms': 96, 'Travel': 96, 'Financial Services': 95, 'ChatGPT Powered': 95, 'Big Data Analytics': 94, 'Advertising': 94, 'Data Security': 93, 'Mac Applications': 91, 'Social Network Media': 90, 'Data Mining': 89, 'Writers': 88, 'Web Browsers': 87, 'Curated Web': 87, 'Direct Sales': 86, 'Online Shopping': 86, 'Job search': 85, 'Cloud Management': 83, 'Content Discovery': 82, 'Online Scheduling': 82, 'Building Products': 81, 'Search': 81, 'Note taking': 80, 'Audio': 79, 'Job Boards': 79, 'Writing tools': 79, 'Publishing': 76, 'E-Commerce Platforms': 76, 'Photo Editing': 76, 'Communications Infrastructure': 76, 'Personal Finance': 76, 'Open Source': 75, 'Service Providers': 73, 'Photography': 72, 'Job Market': 72, 'Podcasting': 72, 'Events': 71, 'AI Copywriting': 71, 'Optimization': 70, 'Services': 70, 'Social CRM': 69, 'Data Privacy': 68, 'Investment Management': 68, 'Social Fundraising': 68, 'IT and Cybersecurity': 67, 'PaaS': 67, 'Subscription Businesses': 66, 'Personal Branding': 64, 'News': 63, 'Social Bookmarking': 62, 'Venture Capital': 62, 'Creative': 61, 'Video Streaming': 61, 'Google Apps': 61, 'Music': 60, 'Reviews and Recommendations': 60, 'Enterprise 2.0': 59, 'Angel Investing': 59, 'Translation': 58, 'Internet': 58, 'Web3': 58, 'Art': 55, 'Android': 55, 'Content Delivery': 55, 'AI Image Processing': 54, 'Digital Media': 54, 'Travel & Tourism': 54, 'Bitcoin': 54, 'Personal Health': 54, 'File Sharing': 53, 'Information Services': 52, 'Billing': 52, 'Big Data': 51, 'Networking': 50, 'Communication Tools': 50, 'Consulting': 50, 'Event Management': 50, 'Social Media Monitoring': 50, 'Geospatial': 49, 'IT Management': 48, 'Professional Networking': 47, 'Creative Industries': 46, 'Productivity': 44, 'Voice': 44, 'Visualization': 44, 'Social Media Platforms': 44, 'AI Development': 43, 'Language Learning': 43, 'Mobile Software Tools': 41, 'Direct Marketing': 40, 'Predictive Analytics': 39, 'Platforms': 39, 'Text Analytics': 38, 'Maps': 38, 'Architecture': 38, 'Training': 38, 'Self Development': 38, 'Internet of Things': 38, 'Video Chat': 38, 'Video Conferencing': 38, 'Learning': 37, 'Trading': 37, 'SMS': 37, 'Mobile Analytics': 37, 'Photo Sharing': 36, 'Health Care': 36, 'Crowdfunding': 36, 'Speech Recognition': 35, 'Usability': 35, 'Real Estate': 35, 'Lifestyle Products': 35, 'Public Relations': 35, 'Consumer Internet': 34, 'Advertising Platforms': 34, 'Monetization': 34, 'Reading Apps': 34, 'Location Based Services': 34, 'Personalization': 33, 'Games': 33, 'Entertainment': 32, 'Social Innovation': 32, 'Business Information Systems': 32, 'Twitter Applications': 32, 'Social Commerce': 32, 'Invest Online': 31, 'Food & Beverages': 31, 'Restaurants': 31, 'Telecommunications': 31, 'Personal Data': 31, 'Stock Exchanges': 31, 'Crowdsourcing': 30, 'Fitness': 30, 'Hardware': 29, 'Information Security': 28, 'Professional Services': 28, 'Enterprises': 28, 'Interior Design': 27, 'Logistics': 27, 'Personal Tools': 27, 'Freemium': 26, 'Virtual Workforces': 26, 'Mobile Devices': 25, 'Utilities': 25, 'Data Centers': 25, 'Retail': 25, 'Unifed Communications': 25, 'Employment': 25, 'Real Time': 25, 'Corporate Training': 25, 'Hospitality': 24, 'Product Search': 24, 'Natural Language Processing': 24, 'All Students': 24, 'Music Services': 24, 'Hardware + Software': 24, 'App Stores': 24, 'iPhone': 24, 'Enterprise Security': 23, 'Identity Management': 23, 'Supply Chain Management': 23, 'Navigation': 23, 'Journalism': 23, 'Families': 23, 'Image Recognition': 22, 'Risk Management': 22, 'Fraud Detection': 22, 'Printing': 22, '3D': 22, 'Fashion': 22, 'Shopping': 22, 'Educational Games': 22, 'Property Management': 22, 'Social Media Advertising': 22, 'Corporate Wellness': 22, 'Health Care Information Technology': 22, 'Polling': 22, 'Human Computer Interaction': 21, 'Retail Technology': 21, 'Construction': 21, 'Virtual Reality': 21, 'Social Search': 21, 'Social Business': 21, 'App Discovery': 21, 'Sports': 21, 'Financial Services Investments': 21, 'Infrastructure': 21, 'Accessibility': 20, 'Gamification': 20, 'Facebook Applications': 20, 'Online Dating': 20, 'Bridging Online and Offline': 20, 'Technical Continuing Education': 19, 'Innovation Engineering': 19, 'Social News': 19, 'Transportation': 19, 'Video on Demand': 19, 'Digital Signage': 18, 'Media': 18, 'Price Comparison': 18, 'K-12 Education': 18, 'Outsourcing': 17, 'Local Businesses': 17, 'Innovation Management': 17, 'Books': 17, 'Sustainability': 17, 'Distribution': 17, 'Licensing': 17, 'Local Search': 17, 'Financial Exchanges': 17, 'Mobile Commerce': 17, 'Musicians': 16, 'Augmented Reality': 16, 'Home Automation': 16, 'Match-Making': 16, 'Workflow Automation': 16, 'NFT': 16, 'Ad Targeting': 16, 'Shared Services': 16, 'Remote Team': 16, 'Mobile Enterprise': 16, 'To Do Lists': 15, 'Online Video Advertising': 15, 'Business Travelers': 15, 'Online Travel': 15, 'Edutainment': 15, 'Deals': 15, 'Embedded Hardware and Software': 15, 'Field Support Services': 15, 'Group SMS': 15, 'Staffing Firms': 15, 'Storage': 14, 'Online Identity': 14, 'Marketing Analytic': 14, 'Mobile Games': 14, 'Smart Building': 14, 'Advertising Networks': 14, 'Ai Tool': 14, 'Competitive Intelligence': 14, 'Procurement': 14, 'Banking': 14, 'Employer Benefits Programs': 14, 'IaaS': 14, 'World': 14, 'Consumer Finance': 14, 'QR Codes': 13, 'Online Gaming': 13, '3D Technology': 13, 'Shipping': 13, 'Film': 13, 'Mobile Video': 13, 'High Tech': 13, 'Adventure Travel': 13, 'Life Sciences': 13, 'Online Reservations': 12, 'Office Space': 12, 'Real Estate Investors': 12, 'Identity': 12, 'Consumers': 12, 'Social Games': 12, 'Q&A': 12, 'Home & Garden': 12, 'Online Events': 12, 'E-Books': 12, 'Coworking': 11, 'Code Generation': 11, 'Semantic Search': 11, 'Quantitative Marketing': 11, 'Artists Globally': 11, 'Loyalty Programs': 11, 'Telephony': 11, 'Green': 11, 'Graphic Design': 11, 'Computers': 11, 'Mobile Advertising': 11, 'Nonprofits': 11, 'Mobile Payments': 11, 'Kids': 11, 'Teachers': 11, 'Ticketing': 11, 'Quantified Self': 11, 'Parenting': 10, 'Point of Sale': 10, 'Mobile Health': 10, 'Engineering Firms': 10, 'Emerging Markets': 10, 'Enterprise Resource Planning': 10, 'CAD': 10, 'EBooks': 10, 'Consumer Goods': 10, 'Intellectual Property': 10, 'Universities': 10, 'University Students': 10, 'Robotics': 10, 'Reputation': 10, 'Visual Search': 10, 'Mobility': 9, 'Social Recruiting': 9, 'Interest Graph': 9, 'Consumer Electronics': 9, 'Promotional': 9, 'Mass Customization': 9, '3D Printing': 9, 'Habit Tracking': 9, 'Peer-to-Peer': 9, 'Local Based Services': 9, 'Local': 9, 'Social Travel': 9, 'Child Care': 9, 'Internet Service Providers': 8, 'Brand Monitoring': 8, 'Portals': 8, 'Semantic Web': 8, 'Entertainment Industry': 8, 'Home Renovation': 8, 'Market Intelligence': 8, 'Gadget': 8, 'Nutrition': 8, 'Forums': 8, 'Tutoring': 8, 'Discounts': 8, 'Comparison Shopping': 8, 'Advice': 8, 'Hedge Funds': 8, 'Lifestyle Businesses': 8, 'Quality Assurance': 8, 'Active Lifestyle': 8, 'Beauty': 8, 'Collectibles': 8, 'Habit Changers': 7, 'Mobile Shopping': 7, 'Compliance': 7, 'Film Production': 7, 'PC Gaming': 7, 'Home Owners': 7, 'Agriculture': 7, 'Local Services': 7, 'Non Profit': 7, 'Online Rental': 7, 'Disruptive Models': 7, 'Wearables': 7, 'Content Generation': 7, 'Content Marketing': 7, 'Computer Vision': 7, 'Temporary Staffing': 7, 'Psychology': 7, 'College Recruiting': 7, 'Social Opinion Platform': 7, 'Sex Industry': 7, 'Conversational Ai': 7, 'Content Creation': 7, 'Biometrics': 6, 'Courses': 6, 'Vacation Rentals': 6, 'Pets': 6, 'Virtual Worlds': 6, 'Home Decor': 6, 'Corporate IT': 6, 'Environmental Innovation': 6, 'Writing Assistant': 6, 'Public Safety': 6, 'Consumer Behavior': 6, 'Guides': 6, 'Cloud-Based Music': 6, 'Insurance': 6, 'Budgeting': 6, 'Video Production': 6, 'Content Syndication': 6, 'Copywriting': 6, 'Healthcare Services': 6, 'Custom Retail': 6, 'Industrial Automation': 6, 'Gift Registries': 6, 'Credit Cards': 6, 'Fleet Management': 6, 'Charity': 6, 'Impact Investing': 6, 'Data Extraction': 5, 'Energy Management': 5, 'Farming': 5, 'Gift Exchange': 5, 'VoIP': 5, 'Wholesale': 5, 'Time Management': 5, 'Time Tracking': 5, 'Charities': 5, 'Incident Management': 5, 'Data Analytic': 5, 'Internet Infrastructure': 5, 'Private School': 5, 'Social Networking': 5, 'Planning': 5, 'General Public Worldwide': 5, 'Hotels': 5, 'Automation': 5, 'Web Analytic': 5, 'Website Builder': 5, 'Integration': 5, 'Automotive': 5, 'Video Games': 5, 'Algorithms': 5, 'Toys': 5, 'Casual Games': 5, 'Gift Card': 5, 'Digital Entertainment': 5, 'Drop-in Audio': 5, 'Data Enrichment': 5, 'Cause Marketing': 5, 'Insurance Companies': 5, 'Operating Systems': 5, 'Realtors': 5, 'Product Discovery': 5, 'MicroBlogging': 4, 'Commercial Real Estate': 4, 'B2B Express Delivery': 4, 'Summarization': 4, 'Food Processing': 4, 'Law Enforcement': 4, 'Image Processing': 4, 'Gps': 4, 'Virtualization': 4, 'Document Automation': 4, 'Rental Housing': 4, 'Colleges': 4, 'Boating Industry': 4, 'DIY': 4, 'Social Media Management': 4, 'Lifestyle Tools': 4, 'Game Mechanics': 4, 'Collaborative Consumption': 4, 'Deep Information Technology': 4, 'Virtual Currency': 4, 'Displays': 4, 'Clean Technology IT': 4, 'Cooking': 4, 'Tablets': 4, 'Lighting': 4, 'Musical Instruments': 4, 'Micro-Enterprises': 4, 'Coffee': 4, 'Internet TV': 4, 'Internet Radio Market': 4, 'Data Collection': 4, 'Portfolio Management': 4, 'Customer Engagement': 4, 'Invoicing': 4, 'Wealth Management': 4, 'Green Building': 4, 'Clean Technology': 4, 'Independent Music': 4, 'Applicant Tracking': 4, 'Directory': 4, 'Sales Intelligence': 4, 'Customer Relationship Management': 4, 'Scheduling': 4, 'Image Generation': 4, 'Alerting': 3, 'Mobile Search': 3, 'Performing Arts': 3, 'Water': 3, 'Manufacturing': 3, 'Idea Management': 3, 'Consumer Lending': 3, 'Communications Hardware': 3, 'Image Editing': 3, 'Aerospace': 3, 'Local Advertising': 3, 'Contract Management': 3, 'Sports Stadiums': 3, 'Fantasy Sports': 3, 'Workforce Management': 3, 'Financial Planning': 3, 'Writing Tool': 3, 'Industrial': 3, 'iPad': 3, 'Recruitment': 3, 'Data Governance': 3, 'Talent Acquisition': 3, 'Incubators': 3, 'FreetoPlay Gaming': 3, 'Campaign Management': 3, 'Energy': 3, 'Space Travel': 3, 'Women': 3, 'Electronics': 3, 'Television': 3, 'Politics': 3, 'Moneymaking': 3, 'Recipes': 3, 'Postal and Courier Services': 3, 'Generative Ai': 3, 'Asset Management': 3, 'Form Builder': 3, 'Music Education': 3, 'Weddings': 3, 'Comics': 3, 'Banking Tech': 3, 'Medical Start Ups': 3, 'Career Development': 3, 'Sales Enablement': 3, 'Visual Design': 2, 'Independent Music Labels': 2, 'Data Quality': 2, 'Solar': 2, 'Clean Energy': 2, 'Matchmaking': 2, 'Onboarding': 2, 'Fintech': 2, 'West Africa': 2, 'East Africa': 2, 'Film Distribution': 2, 'Opinions': 2, 'Medical': 2, 'Diagnostics': 2, 'Flash Sales': 2, 'Funeral Industry': 2, 'Exercise': 2, 'Bioinformatics': 2, 'Document Processing': 2, 'Governments': 2, 'Groceries': 2, 'High School Students': 2, 'Recreation': 2, 'Outdoor Advertising': 2, 'Team Collaboration': 2, 'English Speaking World': 2, 'Workflow Management': 2, 'Release Management': 2, 'Digital Asset Management': 2, 'Assessment': 2, 'Mobile Security': 2, 'Windows Phone 7': 2, 'Clinical Trials': 2, 'Public Transportation': 2, 'Young Adults': 2, 'Advertising Exchanges': 2, 'Cars': 2, 'Medical Marijuana Patients': 2, 'Console Gaming': 2, 'Nightlife': 2, 'Coaching': 2, 'Tourism': 2, 'Government Innovation': 2, 'Animal Feed': 2, 'Conversion Rate Optimization': 2, 'Branding': 2, 'Website Monitoring': 2, 'Transcription': 2, 'Material Science': 2, 'Biotechnology': 2, 'Identity And Access Management': 2, 'Education Technology': 2, 'Documentation': 2, 'Community Building': 2, 'Personal Development': 2, 'Lead Capture': 2, 'Dashboard': 2, 'Cash Flow Management': 2, 'Sponsorship': 2, 'Credit': 2, 'Music Venues': 2, 'Work From Home': 2, 'Senior Health': 2, 'Hospitals': 2, 'High Schools': 2, 'Energy Efficiency': 2, 'Issue Tracking': 2, 'Test Automation': 2, 'Prospecting': 2, 'Talent Management': 2, 'Email Management': 2, 'Customer Support': 2, 'Data Capture': 2, 'Customer Communication': 2, 'Investment Research': 2, 'Expense Tracking': 2, 'Personal Productivity': 2, 'Journaling': 2, 'Inventory Management': 2, 'Search Engine Optimization': 2, 'Physicians': 2, 'NFC': 2, 'Creator Economy': 2, 'Animation': 2, 'User Research': 2, 'MMO Games': 2, 'Content Management': 1, 'Digital Workplace': 1, 'Coupons': 1, 'Advanced Materials': 1, 'Soccer': 1, 'Elder Care': 1, 'Teaching STEM Concepts': 1, 'Humanitarian': 1, 'Parking': 1, 'Market Datum': 1, 'Communication': 1, 'Invention': 1, 'Data Modeling': 1, 'Real Time Collaboration': 1, 'Video Creation': 1, 'Content Repurposing': 1, 'Voice Synthesis': 1, 'Presentation': 1, 'Virtual Goods': 1, 'Reputation Management': 1, 'Software Testing': 1, 'Data Aggregation': 1, 'API Management': 1, 'API Integration': 1, 'Developer Tool': 1, 'Community': 1, 'Surfing Community': 1, 'Skill Gaming': 1, 'Google Glass': 1, 'Hunting Industry': 1, 'Textiles': 1, 'TV Production': 1, 'Developer Experience': 1, 'Vertical Search': 1, 'Craft Beer': 1, 'Wine And Spirits': 1, 'Information Retrieval': 1, 'Cosmetics': 1, 'Social Television': 1, 'Health and Insurance': 1, 'Code Review': 1, 'Data Management': 1, 'Text Analytic': 1, 'Observability': 1, 'Electric Vehicles': 1, 'Marketplace': 1, 'Financial Analytic': 1, 'Medical Devices': 1, 'Pharmaceuticals': 1, 'Widgets': 1, 'Mobile Emergency&Health': 1, 'Dental': 1, 'Drones': 1, 'Brokers': 1, 'Resorts': 1, 'Local Commerce': 1, 'Doctors': 1, 'Medical Professionals': 1, 'Information Organization': 1, 'Hr Technology': 1, 'Email Deliverability': 1, 'Job Board': 1, 'Localization': 1, 'Social Activists': 1, 'Microfinance': 1, 'Classifieds': 1, 'Ventures for Good': 1, 'Appointment Scheduling': 1, 'Meeting Management': 1, 'Gold': 1, 'Vending and Concessions': 1, 'Advertising Technology': 1, 'Operations Management': 1, 'Product Strategy': 1, 'Performance Management': 1, 'Social Media Analytic': 1, 'Reporting': 1, 'Expense Management': 1, 'Calendar': 1, 'Staffing': 1, 'Keyword Research': 1, 'Financial Modeling': 1, 'Business Process Management': 1, 'Customer Feedback': 1, 'Roadmapping': 1, 'Product Management': 1, 'Golf Equipment': 1, 'Diabetes': 1, 'Browser Extension': 1, 'Content Strategy': 1, 'Digital Health': 1, 'Personalized Learning': 1, 'Visual Content Creation': 1, 'Digital Identity': 1, 'Prototyping': 1, 'Privacy Tech': 1, 'Religion': 1, 'Landing Page': 1, 'Growth Marketing': 1, 'Fundraising': 1, 'Behavioral Analytic': 1, 'Mental Health': 1, 'Goal Setting': 1, 'Design Tool': 1, 'Content Sharing': 1, 'Personal Growth': 1, 'Employee Experience': 1, 'Simulation': 1, 'Alternative Medicine': 1, 'Mobile Coupons': 1, 'Indians': 1, 'Bicycles': 1, 'Batteries': 1}

In [ ]:
sorted_topic = dict(sorted(topic_count.items(), key=(lambda x: x[1]), reverse=True))
print(sorted_topic)

{'SaaS': 13137, 'Startups': 7295, 'Web Tools': 5870, 'Developer Tools': 5698, 'Productivity Software': 4966, 'Web Development': 4178, 'Business Productivity': 3805, 'Small and Medium Businesses': 2205, 'Sales and Marketing': 1824, 'Web Design': 1511, 'Artificial Intelligence': 1399, 'Analytics': 1320, 'Apps': 1268, 'B2B': 1118, 'Collaboration': 1093, 'Internet Marketing': 1049, 'Mobile': 888, 'Developer APIs': 881, 'E-Commerce': 848, 'Social Media': 843, 'Development Platforms': 820, 'Design': 804, 'Software': 790, 'Sales Automation': 748, 'Education': 709, 'AI Tools': 681, 'Project Management': 638, 'Technology': 620, 'Business Services': 525, 'Marketing Automation': 494, 'Enterprise Software': 478, 'CRM': 448, 'AI Chat': 443, 'No Code': 409, 'Customer Support Tools': 400, 'User Experience Design': 399, 'Email': 374, 'Web CMS': 372, 'Recruiting': 356, 'Browser Extensions': 343, 'Human Resources': 343, 'Email Marketing': 333, 'Social Media Marketing': 320, 'Chat': 301, 'Freelancers': 285, 'Designers': 285, 'Content Creators': 275, 'Product Design': 274, 'Finance Technology': 268, 'Web Hosting': 266, 'Lead Generation': 255, 'iOS': 255, 'SEO': 238, 'New Product Development': 237, 'Finance': 236, 'Databases': 233, 'Machine Learning': 229, 'Business Analytics': 227, 'Customer Service': 226, 'AI Image Creation': 217, 'Data Integration': 216, 'Tracking': 215, 'Communities': 213, 'Video': 212, 'Remote Work': 201, 'Brand Marketing': 197, 'User Testing': 197, 'Business Intelligence': 191, 'Legal': 186, 'Task Management': 184, 'Marketplaces': 180, 'Document Management': 169, 'Data Visualization': 166, 'Private Social Networking': 165, 'Application Performance Monitoring': 162, 'Cryptocurrencies': 160, 'Business Development': 157, 'Mobile Social': 157, 'Email Newsletters': 155, 'Market Research': 154, 'Blockchain': 153, 'Blogging Platforms': 152, 'Feedback Tools': 152, 'Entrepreneur': 151, 'Domains': 148, 'Human Resource Automation': 147, 'Security': 145, 'Health and Wellness': 139, 'Presentations': 137, 'Content': 136, 'Cloud Data Services': 133, 'Bots': 133, 'Graphics': 130, 'Messaging': 128, 'AI Marketing': 124, 'Meeting Software': 124, 'Lead Management': 119, 'Career Planning': 117, 'Video Editing': 115, 'Cloud Computing': 113, 'Cloud Infrastructure': 112, 'Information Technology': 109, 'Privacy': 108, 'Search Marketing': 105, 'Career Management': 105, 'Knowledge Management': 103, 'Cyber Security': 101, 'AI Assistant': 101, 'Performance Marketing': 100, 'Lifestyle': 100, 'Payments': 100, 'Contact Management': 97, 'Test and Measurement': 97, 'Accounting': 97, 'Application Platforms': 96, 'Travel': 96, 'Financial Services': 95, 'ChatGPT Powered': 95, 'Big Data Analytics': 94, 'Advertising': 94, 'Data Security': 93, 'Mac Applications': 91, 'Social Network Media': 90, 'Data Mining': 89, 'Writers': 88, 'Web Browsers': 87, 'Curated Web': 87, 'Direct Sales': 86, 'Online Shopping': 86, 'Job search': 85, 'Cloud Management': 83, 'Content Discovery': 82, 'Online Scheduling': 82, 'Building Products': 81, 'Search': 81, 'Note taking': 80, 'Audio': 79, 'Job Boards': 79, 'Writing tools': 79, 'Publishing': 76, 'E-Commerce Platforms': 76, 'Photo Editing': 76, 'Communications Infrastructure': 76, 'Personal Finance': 76, 'Open Source': 75, 'Service Providers': 73, 'Photography': 72, 'Job Market': 72, 'Podcasting': 72, 'Events': 71, 'AI Copywriting': 71, 'Optimization': 70, 'Services': 70, 'Social CRM': 69, 'Data Privacy': 68, 'Investment Management': 68, 'Social Fundraising': 68, 'IT and Cybersecurity': 67, 'PaaS': 67, 'Subscription Businesses': 66, 'Personal Branding': 64, 'News': 63, 'Social Bookmarking': 62, 'Venture Capital': 62, 'Creative': 61, 'Video Streaming': 61, 'Google Apps': 61, 'Music': 60, 'Reviews and Recommendations': 60, 'Enterprise 2.0': 59, 'Angel Investing': 59, 'Translation': 58, 'Internet': 58, 'Web3': 58, 'Art': 55, 'Android': 55, 'Content Delivery': 55, 'AI Image Processing': 54, 'Digital Media': 54, 'Travel & Tourism': 54, 'Bitcoin': 54, 'Personal Health': 54, 'File Sharing': 53, 'Information Services': 52, 'Billing': 52, 'Big Data': 51, 'Networking': 50, 'Communication Tools': 50, 'Consulting': 50, 'Event Management': 50, 'Social Media Monitoring': 50, 'Geospatial': 49, 'IT Management': 48, 'Professional Networking': 47, 'Creative Industries': 46, 'Productivity': 44, 'Voice': 44, 'Visualization': 44, 'Social Media Platforms': 44, 'AI Development': 43, 'Language Learning': 43, 'Mobile Software Tools': 41, 'Direct Marketing': 40, 'Predictive Analytics': 39, 'Platforms': 39, 'Text Analytics': 38, 'Maps': 38, 'Architecture': 38, 'Training': 38, 'Self Development': 38, 'Internet of Things': 38, 'Video Chat': 38, 'Video Conferencing': 38, 'Learning': 37, 'Trading': 37, 'SMS': 37, 'Mobile Analytics': 37, 'Photo Sharing': 36, 'Health Care': 36, 'Crowdfunding': 36, 'Speech Recognition': 35, 'Usability': 35, 'Real Estate': 35, 'Lifestyle Products': 35, 'Public Relations': 35, 'Consumer Internet': 34, 'Advertising Platforms': 34, 'Monetization': 34, 'Reading Apps': 34, 'Location Based Services': 34, 'Personalization': 33, 'Games': 33, 'Entertainment': 32, 'Social Innovation': 32, 'Business Information Systems': 32, 'Twitter Applications': 32, 'Social Commerce': 32, 'Invest Online': 31, 'Food & Beverages': 31, 'Restaurants': 31, 'Telecommunications': 31, 'Personal Data': 31, 'Stock Exchanges': 31, 'Crowdsourcing': 30, 'Fitness': 30, 'Hardware': 29, 'Information Security': 28, 'Professional Services': 28, 'Enterprises': 28, 'Interior Design': 27, 'Logistics': 27, 'Personal Tools': 27, 'Freemium': 26, 'Virtual Workforces': 26, 'Mobile Devices': 25, 'Utilities': 25, 'Data Centers': 25, 'Retail': 25, 'Unifed Communications': 25, 'Employment': 25, 'Real Time': 25, 'Corporate Training': 25, 'Hospitality': 24, 'Product Search': 24, 'Natural Language Processing': 24, 'All Students': 24, 'Music Services': 24, 'Hardware + Software': 24, 'App Stores': 24, 'iPhone': 24, 'Enterprise Security': 23, 'Identity Management': 23, 'Supply Chain Management': 23, 'Navigation': 23, 'Journalism': 23, 'Families': 23, 'Image Recognition': 22, 'Risk Management': 22, 'Fraud Detection': 22, 'Printing': 22, '3D': 22, 'Fashion': 22, 'Shopping': 22, 'Educational Games': 22, 'Property Management': 22, 'Social Media Advertising': 22, 'Corporate Wellness': 22, 'Health Care Information Technology': 22, 'Polling': 22, 'Human Computer Interaction': 21, 'Retail Technology': 21, 'Construction': 21, 'Virtual Reality': 21, 'Social Search': 21, 'Social Business': 21, 'App Discovery': 21, 'Sports': 21, 'Financial Services Investments': 21, 'Infrastructure': 21, 'Accessibility': 20, 'Gamification': 20, 'Facebook Applications': 20, 'Online Dating': 20, 'Bridging Online and Offline': 20, 'Technical Continuing Education': 19, 'Innovation Engineering': 19, 'Social News': 19, 'Transportation': 19, 'Video on Demand': 19, 'Digital Signage': 18, 'Media': 18, 'Price Comparison': 18, 'K-12 Education': 18, 'Outsourcing': 17, 'Local Businesses': 17, 'Innovation Management': 17, 'Books': 17, 'Sustainability': 17, 'Distribution': 17, 'Licensing': 17, 'Local Search': 17, 'Financial Exchanges': 17, 'Mobile Commerce': 17, 'Musicians': 16, 'Augmented Reality': 16, 'Home Automation': 16, 'Match-Making': 16, 'Workflow Automation': 16, 'NFT': 16, 'Ad Targeting': 16, 'Shared Services': 16, 'Remote Team': 16, 'Mobile Enterprise': 16, 'To Do Lists': 15, 'Online Video Advertising': 15, 'Business Travelers': 15, 'Online Travel': 15, 'Edutainment': 15, 'Deals': 15, 'Embedded Hardware and Software': 15, 'Field Support Services': 15, 'Group SMS': 15, 'Staffing Firms': 15, 'Storage': 14, 'Online Identity': 14, 'Marketing Analytic': 14, 'Mobile Games': 14, 'Smart Building': 14, 'Advertising Networks': 14, 'Ai Tool': 14, 'Competitive Intelligence': 14, 'Procurement': 14, 'Banking': 14, 'Employer Benefits Programs': 14, 'IaaS': 14, 'World': 14, 'Consumer Finance': 14, 'QR Codes': 13, 'Online Gaming': 13, '3D Technology': 13, 'Shipping': 13, 'Film': 13, 'Mobile Video': 13, 'High Tech': 13, 'Adventure Travel': 13, 'Life Sciences': 13, 'Online Reservations': 12, 'Office Space': 12, 'Real Estate Investors': 12, 'Identity': 12, 'Consumers': 12, 'Social Games': 12, 'Q&A': 12, 'Home & Garden': 12, 'Online Events': 12, 'E-Books': 12, 'Coworking': 11, 'Code Generation': 11, 'Semantic Search': 11, 'Quantitative Marketing': 11, 'Artists Globally': 11, 'Loyalty Programs': 11, 'Telephony': 11, 'Green': 11, 'Graphic Design': 11, 'Computers': 11, 'Mobile Advertising': 11, 'Nonprofits': 11, 'Mobile Payments': 11, 'Kids': 11, 'Teachers': 11, 'Ticketing': 11, 'Quantified Self': 11, 'Parenting': 10, 'Point of Sale': 10, 'Mobile Health': 10, 'Engineering Firms': 10, 'Emerging Markets': 10, 'Enterprise Resource Planning': 10, 'CAD': 10, 'EBooks': 10, 'Consumer Goods': 10, 'Intellectual Property': 10, 'Universities': 10, 'University Students': 10, 'Robotics': 10, 'Reputation': 10, 'Visual Search': 10, 'Mobility': 9, 'Social Recruiting': 9, 'Interest Graph': 9, 'Consumer Electronics': 9, 'Promotional': 9, 'Mass Customization': 9, '3D Printing': 9, 'Habit Tracking': 9, 'Peer-to-Peer': 9, 'Local Based Services': 9, 'Local': 9, 'Social Travel': 9, 'Child Care': 9, 'Internet Service Providers': 8, 'Brand Monitoring': 8, 'Portals': 8, 'Semantic Web': 8, 'Entertainment Industry': 8, 'Home Renovation': 8, 'Market Intelligence': 8, 'Gadget': 8, 'Nutrition': 8, 'Forums': 8, 'Tutoring': 8, 'Discounts': 8, 'Comparison Shopping': 8, 'Advice': 8, 'Hedge Funds': 8, 'Lifestyle Businesses': 8, 'Quality Assurance': 8, 'Active Lifestyle': 8, 'Beauty': 8, 'Collectibles': 8, 'Habit Changers': 7, 'Mobile Shopping': 7, 'Compliance': 7, 'Film Production': 7, 'PC Gaming': 7, 'Home Owners': 7, 'Agriculture': 7, 'Local Services': 7, 'Non Profit': 7, 'Online Rental': 7, 'Disruptive Models': 7, 'Wearables': 7, 'Content Generation': 7, 'Content Marketing': 7, 'Computer Vision': 7, 'Temporary Staffing': 7, 'Psychology': 7, 'College Recruiting': 7, 'Social Opinion Platform': 7, 'Sex Industry': 7, 'Conversational Ai': 7, 'Content Creation': 7, 'Biometrics': 6, 'Courses': 6, 'Vacation Rentals': 6, 'Pets': 6, 'Virtual Worlds': 6, 'Home Decor': 6, 'Corporate IT': 6, 'Environmental Innovation': 6, 'Writing Assistant': 6, 'Public Safety': 6, 'Consumer Behavior': 6, 'Guides': 6, 'Cloud-Based Music': 6, 'Insurance': 6, 'Budgeting': 6, 'Video Production': 6, 'Content Syndication': 6, 'Copywriting': 6, 'Healthcare Services': 6, 'Custom Retail': 6, 'Industrial Automation': 6, 'Gift Registries': 6, 'Credit Cards': 6, 'Fleet Management': 6, 'Charity': 6, 'Impact Investing': 6, 'Data Extraction': 5, 'Energy Management': 5, 'Farming': 5, 'Gift Exchange': 5, 'VoIP': 5, 'Wholesale': 5, 'Time Management': 5, 'Time Tracking': 5, 'Charities': 5, 'Incident Management': 5, 'Data Analytic': 5, 'Internet Infrastructure': 5, 'Private School': 5, 'Social Networking': 5, 'Planning': 5, 'General Public Worldwide': 5, 'Hotels': 5, 'Automation': 5, 'Web Analytic': 5, 'Website Builder': 5, 'Integration': 5, 'Automotive': 5, 'Video Games': 5, 'Algorithms': 5, 'Toys': 5, 'Casual Games': 5, 'Gift Card': 5, 'Digital Entertainment': 5, 'Drop-in Audio': 5, 'Data Enrichment': 5, 'Cause Marketing': 5, 'Insurance Companies': 5, 'Operating Systems': 5, 'Realtors': 5, 'Product Discovery': 5, 'MicroBlogging': 4, 'Commercial Real Estate': 4, 'B2B Express Delivery': 4, 'Summarization': 4, 'Food Processing': 4, 'Law Enforcement': 4, 'Image Processing': 4, 'Gps': 4, 'Virtualization': 4, 'Document Automation': 4, 'Rental Housing': 4, 'Colleges': 4, 'Boating Industry': 4, 'DIY': 4, 'Social Media Management': 4, 'Lifestyle Tools': 4, 'Game Mechanics': 4, 'Collaborative Consumption': 4, 'Deep Information Technology': 4, 'Virtual Currency': 4, 'Displays': 4, 'Clean Technology IT': 4, 'Cooking': 4, 'Tablets': 4, 'Lighting': 4, 'Musical Instruments': 4, 'Micro-Enterprises': 4, 'Coffee': 4, 'Internet TV': 4, 'Internet Radio Market': 4, 'Data Collection': 4, 'Portfolio Management': 4, 'Customer Engagement': 4, 'Invoicing': 4, 'Wealth Management': 4, 'Green Building': 4, 'Clean Technology': 4, 'Independent Music': 4, 'Applicant Tracking': 4, 'Directory': 4, 'Sales Intelligence': 4, 'Customer Relationship Management': 4, 'Scheduling': 4, 'Image Generation': 4, 'Alerting': 3, 'Mobile Search': 3, 'Performing Arts': 3, 'Water': 3, 'Manufacturing': 3, 'Idea Management': 3, 'Consumer Lending': 3, 'Communications Hardware': 3, 'Image Editing': 3, 'Aerospace': 3, 'Local Advertising': 3, 'Contract Management': 3, 'Sports Stadiums': 3, 'Fantasy Sports': 3, 'Workforce Management': 3, 'Financial Planning': 3, 'Writing Tool': 3, 'Industrial': 3, 'iPad': 3, 'Recruitment': 3, 'Data Governance': 3, 'Talent Acquisition': 3, 'Incubators': 3, 'FreetoPlay Gaming': 3, 'Campaign Management': 3, 'Energy': 3, 'Space Travel': 3, 'Women': 3, 'Electronics': 3, 'Television': 3, 'Politics': 3, 'Moneymaking': 3, 'Recipes': 3, 'Postal and Courier Services': 3, 'Generative Ai': 3, 'Asset Management': 3, 'Form Builder': 3, 'Music Education': 3, 'Weddings': 3, 'Comics': 3, 'Banking Tech': 3, 'Medical Start Ups': 3, 'Career Development': 3, 'Sales Enablement': 3, 'Visual Design': 2, 'Independent Music Labels': 2, 'Data Quality': 2, 'Solar': 2, 'Clean Energy': 2, 'Matchmaking': 2, 'Onboarding': 2, 'Fintech': 2, 'West Africa': 2, 'East Africa': 2, 'Film Distribution': 2, 'Opinions': 2, 'Medical': 2, 'Diagnostics': 2, 'Flash Sales': 2, 'Funeral Industry': 2, 'Exercise': 2, 'Bioinformatics': 2, 'Document Processing': 2, 'Governments': 2, 'Groceries': 2, 'High School Students': 2, 'Recreation': 2, 'Outdoor Advertising': 2, 'Team Collaboration': 2, 'English Speaking World': 2, 'Workflow Management': 2, 'Release Management': 2, 'Digital Asset Management': 2, 'Assessment': 2, 'Mobile Security': 2, 'Windows Phone 7': 2, 'Clinical Trials': 2, 'Public Transportation': 2, 'Young Adults': 2, 'Advertising Exchanges': 2, 'Cars': 2, 'Medical Marijuana Patients': 2, 'Console Gaming': 2, 'Nightlife': 2, 'Coaching': 2, 'Tourism': 2, 'Government Innovation': 2, 'Animal Feed': 2, 'Conversion Rate Optimization': 2, 'Branding': 2, 'Website Monitoring': 2, 'Transcription': 2, 'Material Science': 2, 'Biotechnology': 2, 'Identity And Access Management': 2, 'Education Technology': 2, 'Documentation': 2, 'Community Building': 2, 'Personal Development': 2, 'Lead Capture': 2, 'Dashboard': 2, 'Cash Flow Management': 2, 'Sponsorship': 2, 'Credit': 2, 'Music Venues': 2, 'Work From Home': 2, 'Senior Health': 2, 'Hospitals': 2, 'High Schools': 2, 'Energy Efficiency': 2, 'Issue Tracking': 2, 'Test Automation': 2, 'Prospecting': 2, 'Talent Management': 2, 'Email Management': 2, 'Customer Support': 2, 'Data Capture': 2, 'Customer Communication': 2, 'Investment Research': 2, 'Expense Tracking': 2, 'Personal Productivity': 2, 'Journaling': 2, 'Inventory Management': 2, 'Search Engine Optimization': 2, 'Physicians': 2, 'NFC': 2, 'Creator Economy': 2, 'Animation': 2, 'User Research': 2, 'MMO Games': 2, 'Content Management': 1, 'Digital Workplace': 1, 'Coupons': 1, 'Advanced Materials': 1, 'Soccer': 1, 'Elder Care': 1, 'Teaching STEM Concepts': 1, 'Humanitarian': 1, 'Parking': 1, 'Market Datum': 1, 'Communication': 1, 'Invention': 1, 'Data Modeling': 1, 'Real Time Collaboration': 1, 'Video Creation': 1, 'Content Repurposing': 1, 'Voice Synthesis': 1, 'Presentation': 1, 'Virtual Goods': 1, 'Reputation Management': 1, 'Software Testing': 1, 'Data Aggregation': 1, 'API Management': 1, 'API Integration': 1, 'Developer Tool': 1, 'Community': 1, 'Surfing Community': 1, 'Skill Gaming': 1, 'Google Glass': 1, 'Hunting Industry': 1, 'Textiles': 1, 'TV Production': 1, 'Developer Experience': 1, 'Vertical Search': 1, 'Craft Beer': 1, 'Wine And Spirits': 1, 'Information Retrieval': 1, 'Cosmetics': 1, 'Social Television': 1, 'Health and Insurance': 1, 'Code Review': 1, 'Data Management': 1, 'Text Analytic': 1, 'Observability': 1, 'Electric Vehicles': 1, 'Marketplace': 1, 'Financial Analytic': 1, 'Medical Devices': 1, 'Pharmaceuticals': 1, 'Widgets': 1, 'Mobile Emergency&Health': 1, 'Dental': 1, 'Drones': 1, 'Brokers': 1, 'Resorts': 1, 'Local Commerce': 1, 'Doctors': 1, 'Medical Professionals': 1, 'Information Organization': 1, 'Hr Technology': 1, 'Email Deliverability': 1, 'Job Board': 1, 'Localization': 1, 'Social Activists': 1, 'Microfinance': 1, 'Classifieds': 1, 'Ventures for Good': 1, 'Appointment Scheduling': 1, 'Meeting Management': 1, 'Gold': 1, 'Vending and Concessions': 1, 'Advertising Technology': 1, 'Operations Management': 1, 'Product Strategy': 1, 'Performance Management': 1, 'Social Media Analytic': 1, 'Reporting': 1, 'Expense Management': 1, 'Calendar': 1, 'Staffing': 1, 'Keyword Research': 1, 'Financial Modeling': 1, 'Business Process Management': 1, 'Customer Feedback': 1, 'Roadmapping': 1, 'Product Management': 1, 'Golf Equipment': 1, 'Diabetes': 1, 'Browser Extension': 1, 'Content Strategy': 1, 'Digital Health': 1, 'Personalized Learning': 1, 'Visual Content Creation': 1, 'Digital Identity': 1, 'Prototyping': 1, 'Privacy Tech': 1, 'Religion': 1, 'Landing Page': 1, 'Growth Marketing': 1, 'Fundraising': 1, 'Behavioral Analytic': 1, 'Mental Health': 1, 'Goal Setting': 1, 'Design Tool': 1, 'Content Sharing': 1, 'Personal Growth': 1, 'Employee Experience': 1, 'Simulation': 1, 'Alternative Medicine': 1, 'Mobile Coupons': 1, 'Indians': 1, 'Bicycles': 1, 'Batteries': 1}

In [ ]:
#sorted_topic

In [ ]:
# Filter low-occurrence labels
threshold = int(len(df) * 0.00467)
rare_topics = [key for key, value in sorted_topic.items() if value < threshold]

In [ ]:
len(rare_topics)

700

In [ ]:
print(rare_topics)

['Contact Management', 'Test and Measurement', 'Accounting', 'Application Platforms', 'Travel', 'Financial Services', 'ChatGPT Powered', 'Big Data Analytics', 'Advertising', 'Data Security', 'Mac Applications', 'Social Network Media', 'Data Mining', 'Writers', 'Web Browsers', 'Curated Web', 'Direct Sales', 'Online Shopping', 'Job search', 'Cloud Management', 'Content Discovery', 'Online Scheduling', 'Building Products', 'Search', 'Note taking', 'Audio', 'Job Boards', 'Writing tools', 'Publishing', 'E-Commerce Platforms', 'Photo Editing', 'Communications Infrastructure', 'Personal Finance', 'Open Source', 'Service Providers', 'Photography', 'Job Market', 'Podcasting', 'Events', 'AI Copywriting', 'Optimization', 'Services', 'Social CRM', 'Data Privacy', 'Investment Management', 'Social Fundraising', 'IT and Cybersecurity', 'PaaS', 'Subscription Businesses', 'Personal Branding', 'News', 'Social Bookmarking', 'Venture Capital', 'Creative', 'Video Streaming', 'Google Apps', 'Music', 'Reviews and Recommendations', 'Enterprise 2.0', 'Angel Investing', 'Translation', 'Internet', 'Web3', 'Art', 'Android', 'Content Delivery', 'AI Image Processing', 'Digital Media', 'Travel & Tourism', 'Bitcoin', 'Personal Health', 'File Sharing', 'Information Services', 'Billing', 'Big Data', 'Networking', 'Communication Tools', 'Consulting', 'Event Management', 'Social Media Monitoring', 'Geospatial', 'IT Management', 'Professional Networking', 'Creative Industries', 'Productivity', 'Voice', 'Visualization', 'Social Media Platforms', 'AI Development', 'Language Learning', 'Mobile Software Tools', 'Direct Marketing', 'Predictive Analytics', 'Platforms', 'Text Analytics', 'Maps', 'Architecture', 'Training', 'Self Development', 'Internet of Things', 'Video Chat', 'Video Conferencing', 'Learning', 'Trading', 'SMS', 'Mobile Analytics', 'Photo Sharing', 'Health Care', 'Crowdfunding', 'Speech Recognition', 'Usability', 'Real Estate', 'Lifestyle Products', 'Public Relations', 'Consumer Internet', 'Advertising Platforms', 'Monetization', 'Reading Apps', 'Location Based Services', 'Personalization', 'Games', 'Entertainment', 'Social Innovation', 'Business Information Systems', 'Twitter Applications', 'Social Commerce', 'Invest Online', 'Food & Beverages', 'Restaurants', 'Telecommunications', 'Personal Data', 'Stock Exchanges', 'Crowdsourcing', 'Fitness', 'Hardware', 'Information Security', 'Professional Services', 'Enterprises', 'Interior Design', 'Logistics', 'Personal Tools', 'Freemium', 'Virtual Workforces', 'Mobile Devices', 'Utilities', 'Data Centers', 'Retail', 'Unifed Communications', 'Employment', 'Real Time', 'Corporate Training', 'Hospitality', 'Product Search', 'Natural Language Processing', 'All Students', 'Music Services', 'Hardware + Software', 'App Stores', 'iPhone', 'Enterprise Security', 'Identity Management', 'Supply Chain Management', 'Navigation', 'Journalism', 'Families', 'Image Recognition', 'Risk Management', 'Fraud Detection', 'Printing', '3D', 'Fashion', 'Shopping', 'Educational Games', 'Property Management', 'Social Media Advertising', 'Corporate Wellness', 'Health Care Information Technology', 'Polling', 'Human Computer Interaction', 'Retail Technology', 'Construction', 'Virtual Reality', 'Social Search', 'Social Business', 'App Discovery', 'Sports', 'Financial Services Investments', 'Infrastructure', 'Accessibility', 'Gamification', 'Facebook Applications', 'Online Dating', 'Bridging Online and Offline', 'Technical Continuing Education', 'Innovation Engineering', 'Social News', 'Transportation', 'Video on Demand', 'Digital Signage', 'Media', 'Price Comparison', 'K-12 Education', 'Outsourcing', 'Local Businesses', 'Innovation Management', 'Books', 'Sustainability', 'Distribution', 'Licensing', 'Local Search', 'Financial Exchanges', 'Mobile Commerce', 'Musicians', 'Augmented Reality', 'Home Automation', 'Match-Making', 'Workflow Automation', 'NFT', 'Ad Targeting', 'Shared Services', 'Remote Team', 'Mobile Enterprise', 'To Do Lists', 'Online Video Advertising', 'Business Travelers', 'Online Travel', 'Edutainment', 'Deals', 'Embedded Hardware and Software', 'Field Support Services', 'Group SMS', 'Staffing Firms', 'Storage', 'Online Identity', 'Marketing Analytic', 'Mobile Games', 'Smart Building', 'Advertising Networks', 'Ai Tool', 'Competitive Intelligence', 'Procurement', 'Banking', 'Employer Benefits Programs', 'IaaS', 'World', 'Consumer Finance', 'QR Codes', 'Online Gaming', '3D Technology', 'Shipping', 'Film', 'Mobile Video', 'High Tech', 'Adventure Travel', 'Life Sciences', 'Online Reservations', 'Office Space', 'Real Estate Investors', 'Identity', 'Consumers', 'Social Games', 'Q&A', 'Home & Garden', 'Online Events', 'E-Books', 'Coworking', 'Code Generation', 'Semantic Search', 'Quantitative Marketing', 'Artists Globally', 'Loyalty Programs', 'Telephony', 'Green', 'Graphic Design', 'Computers', 'Mobile Advertising', 'Nonprofits', 'Mobile Payments', 'Kids', 'Teachers', 'Ticketing', 'Quantified Self', 'Parenting', 'Point of Sale', 'Mobile Health', 'Engineering Firms', 'Emerging Markets', 'Enterprise Resource Planning', 'CAD', 'EBooks', 'Consumer Goods', 'Intellectual Property', 'Universities', 'University Students', 'Robotics', 'Reputation', 'Visual Search', 'Mobility', 'Social Recruiting', 'Interest Graph', 'Consumer Electronics', 'Promotional', 'Mass Customization', '3D Printing', 'Habit Tracking', 'Peer-to-Peer', 'Local Based Services', 'Local', 'Social Travel', 'Child Care', 'Internet Service Providers', 'Brand Monitoring', 'Portals', 'Semantic Web', 'Entertainment Industry', 'Home Renovation', 'Market Intelligence', 'Gadget', 'Nutrition', 'Forums', 'Tutoring', 'Discounts', 'Comparison Shopping', 'Advice', 'Hedge Funds', 'Lifestyle Businesses', 'Quality Assurance', 'Active Lifestyle', 'Beauty', 'Collectibles', 'Habit Changers', 'Mobile Shopping', 'Compliance', 'Film Production', 'PC Gaming', 'Home Owners', 'Agriculture', 'Local Services', 'Non Profit', 'Online Rental', 'Disruptive Models', 'Wearables', 'Content Generation', 'Content Marketing', 'Computer Vision', 'Temporary Staffing', 'Psychology', 'College Recruiting', 'Social Opinion Platform', 'Sex Industry', 'Conversational Ai', 'Content Creation', 'Biometrics', 'Courses', 'Vacation Rentals', 'Pets', 'Virtual Worlds', 'Home Decor', 'Corporate IT', 'Environmental Innovation', 'Writing Assistant', 'Public Safety', 'Consumer Behavior', 'Guides', 'Cloud-Based Music', 'Insurance', 'Budgeting', 'Video Production', 'Content Syndication', 'Copywriting', 'Healthcare Services', 'Custom Retail', 'Industrial Automation', 'Gift Registries', 'Credit Cards', 'Fleet Management', 'Charity', 'Impact Investing', 'Data Extraction', 'Energy Management', 'Farming', 'Gift Exchange', 'VoIP', 'Wholesale', 'Time Management', 'Time Tracking', 'Charities', 'Incident Management', 'Data Analytic', 'Internet Infrastructure', 'Private School', 'Social Networking', 'Planning', 'General Public Worldwide', 'Hotels', 'Automation', 'Web Analytic', 'Website Builder', 'Integration', 'Automotive', 'Video Games', 'Algorithms', 'Toys', 'Casual Games', 'Gift Card', 'Digital Entertainment', 'Drop-in Audio', 'Data Enrichment', 'Cause Marketing', 'Insurance Companies', 'Operating Systems', 'Realtors', 'Product Discovery', 'MicroBlogging', 'Commercial Real Estate', 'B2B Express Delivery', 'Summarization', 'Food Processing', 'Law Enforcement', 'Image Processing', 'Gps', 'Virtualization', 'Document Automation', 'Rental Housing', 'Colleges', 'Boating Industry', 'DIY', 'Social Media Management', 'Lifestyle Tools', 'Game Mechanics', 'Collaborative Consumption', 'Deep Information Technology', 'Virtual Currency', 'Displays', 'Clean Technology IT', 'Cooking', 'Tablets', 'Lighting', 'Musical Instruments', 'Micro-Enterprises', 'Coffee', 'Internet TV', 'Internet Radio Market', 'Data Collection', 'Portfolio Management', 'Customer Engagement', 'Invoicing', 'Wealth Management', 'Green Building', 'Clean Technology', 'Independent Music', 'Applicant Tracking', 'Directory', 'Sales Intelligence', 'Customer Relationship Management', 'Scheduling', 'Image Generation', 'Alerting', 'Mobile Search', 'Performing Arts', 'Water', 'Manufacturing', 'Idea Management', 'Consumer Lending', 'Communications Hardware', 'Image Editing', 'Aerospace', 'Local Advertising', 'Contract Management', 'Sports Stadiums', 'Fantasy Sports', 'Workforce Management', 'Financial Planning', 'Writing Tool', 'Industrial', 'iPad', 'Recruitment', 'Data Governance', 'Talent Acquisition', 'Incubators', 'FreetoPlay Gaming', 'Campaign Management', 'Energy', 'Space Travel', 'Women', 'Electronics', 'Television', 'Politics', 'Moneymaking', 'Recipes', 'Postal and Courier Services', 'Generative Ai', 'Asset Management', 'Form Builder', 'Music Education', 'Weddings', 'Comics', 'Banking Tech', 'Medical Start Ups', 'Career Development', 'Sales Enablement', 'Visual Design', 'Independent Music Labels', 'Data Quality', 'Solar', 'Clean Energy', 'Matchmaking', 'Onboarding', 'Fintech', 'West Africa', 'East Africa', 'Film Distribution', 'Opinions', 'Medical', 'Diagnostics', 'Flash Sales', 'Funeral Industry', 'Exercise', 'Bioinformatics', 'Document Processing', 'Governments', 'Groceries', 'High School Students', 'Recreation', 'Outdoor Advertising', 'Team Collaboration', 'English Speaking World', 'Workflow Management', 'Release Management', 'Digital Asset Management', 'Assessment', 'Mobile Security', 'Windows Phone 7', 'Clinical Trials', 'Public Transportation', 'Young Adults', 'Advertising Exchanges', 'Cars', 'Medical Marijuana Patients', 'Console Gaming', 'Nightlife', 'Coaching', 'Tourism', 'Government Innovation', 'Animal Feed', 'Conversion Rate Optimization', 'Branding', 'Website Monitoring', 'Transcription', 'Material Science', 'Biotechnology', 'Identity And Access Management', 'Education Technology', 'Documentation', 'Community Building', 'Personal Development', 'Lead Capture', 'Dashboard', 'Cash Flow Management', 'Sponsorship', 'Credit', 'Music Venues', 'Work From Home', 'Senior Health', 'Hospitals', 'High Schools', 'Energy Efficiency', 'Issue Tracking', 'Test Automation', 'Prospecting', 'Talent Management', 'Email Management', 'Customer Support', 'Data Capture', 'Customer Communication', 'Investment Research', 'Expense Tracking', 'Personal Productivity', 'Journaling', 'Inventory Management', 'Search Engine Optimization', 'Physicians', 'NFC', 'Creator Economy', 'Animation', 'User Research', 'MMO Games', 'Content Management', 'Digital Workplace', 'Coupons', 'Advanced Materials', 'Soccer', 'Elder Care', 'Teaching STEM Concepts', 'Humanitarian', 'Parking', 'Market Datum', 'Communication', 'Invention', 'Data Modeling', 'Real Time Collaboration', 'Video Creation', 'Content Repurposing', 'Voice Synthesis', 'Presentation', 'Virtual Goods', 'Reputation Management', 'Software Testing', 'Data Aggregation', 'API Management', 'API Integration', 'Developer Tool', 'Community', 'Surfing Community', 'Skill Gaming', 'Google Glass', 'Hunting Industry', 'Textiles', 'TV Production', 'Developer Experience', 'Vertical Search', 'Craft Beer', 'Wine And Spirits', 'Information Retrieval', 'Cosmetics', 'Social Television', 'Health and Insurance', 'Code Review', 'Data Management', 'Text Analytic', 'Observability', 'Electric Vehicles', 'Marketplace', 'Financial Analytic', 'Medical Devices', 'Pharmaceuticals', 'Widgets', 'Mobile Emergency&Health', 'Dental', 'Drones', 'Brokers', 'Resorts', 'Local Commerce', 'Doctors', 'Medical Professionals', 'Information Organization', 'Hr Technology', 'Email Deliverability', 'Job Board', 'Localization', 'Social Activists', 'Microfinance', 'Classifieds', 'Ventures for Good', 'Appointment Scheduling', 'Meeting Management', 'Gold', 'Vending and Concessions', 'Advertising Technology', 'Operations Management', 'Product Strategy', 'Performance Management', 'Social Media Analytic', 'Reporting', 'Expense Management', 'Calendar', 'Staffing', 'Keyword Research', 'Financial Modeling', 'Business Process Management', 'Customer Feedback', 'Roadmapping', 'Product Management', 'Golf Equipment', 'Diabetes', 'Browser Extension', 'Content Strategy', 'Digital Health', 'Personalized Learning', 'Visual Content Creation', 'Digital Identity', 'Prototyping', 'Privacy Tech', 'Religion', 'Landing Page', 'Growth Marketing', 'Fundraising', 'Behavioral Analytic', 'Mental Health', 'Goal Setting', 'Design Tool', 'Content Sharing', 'Personal Growth', 'Employee Experience', 'Simulation', 'Alternative Medicine', 'Mobile Coupons', 'Indians', 'Bicycles', 'Batteries']

In [ ]:
topics_list = df.topics.to_list()

revised_topic_list = []
indices_to_drop = []

for idx, topics in enumerate(topics_list):
  revised_topics = [topic.strip() for topic in topics.split(',') if topic.strip() not in rare_topics]
  if len(revised_topics) == 0:
    indices_to_drop.append(idx)
  else:
    revised_topic_list.append(revised_topics)

In [ ]:
len(revised_topic_list)

21353

In [ ]:
df = df.drop(indices_to_drop).reset_index(drop=True)
# Save cleaned topics back to dataframe
df["topics"] = revised_topic_list
print(df.shape)

(21353, 5)

In [ ]:
df.head()

,name,motto,description,topics,url
0,Flux Plugins,"Speed up WordPress with AI-powered image, SEO,...",Flux Plugins provides a suite of WordPress plu...,"[Blogging Platforms, Performance Marketing, SEO]",https://betalist.com/startups/flux-plugins
1,Wafaa.io BOOSTED,Create digital contracts in minutes,Wafaa is your new one-stop shop for digital co...,"[SaaS, B2B, Freelancers]",https://betalist.com/startups/wafaa-io
2,Vaulternal,Store and automate file access with secure fil...,"Vaulternal offers encrypted, decentralized fil...","[Lifestyle, SaaS]",https://betalist.com/startups/vaulternal
3,PUBVOICE,Turn your articles into audio and boost reader...,PUBVOICE converts your articles into high-qual...,[Analytics],https://betalist.com/startups/pubvoice
4,OPT-IMG,"AI tool to optimize images for SEO, speed, and...",OPT-IMG is an AI-powered image SEO platform th...,[SEO],https://betalist.com/startups/opt-img

In [ ]:
revised_topics_list = df.topics.to_list()
revised_topic_count = {}
for topics in revised_topics_list:
  topic_list = topics
  for topic in topic_list:
    if topic in revised_topic_count.keys():
      revised_topic_count[topic] += 1
    else:
      revised_topic_count[topic] = 1
print(f"Number of topics: {len(revised_topic_count)}")
print(dict(sorted(revised_topic_count.items(), key=lambda x:x[1], reverse=True)))

Number of topics: 111
{'SaaS': 13137, 'Startups': 7295, 'Web Tools': 5870, 'Developer Tools': 5698, 'Productivity Software': 4966, 'Web Development': 4178, 'Business Productivity': 3805, 'Small and Medium Businesses': 2205, 'Sales and Marketing': 1824, 'Web Design': 1511, 'Artificial Intelligence': 1399, 'Analytics': 1320, 'Apps': 1268, 'B2B': 1118, 'Collaboration': 1093, 'Internet Marketing': 1049, 'Mobile': 888, 'Developer APIs': 881, 'E-Commerce': 848, 'Social Media': 843, 'Development Platforms': 820, 'Design': 804, 'Software': 790, 'Sales Automation': 748, 'Education': 709, 'AI Tools': 681, 'Project Management': 638, 'Technology': 620, 'Business Services': 525, 'Marketing Automation': 494, 'Enterprise Software': 478, 'CRM': 448, 'AI Chat': 443, 'No Code': 409, 'Customer Support Tools': 400, 'User Experience Design': 399, 'Email': 374, 'Web CMS': 372, 'Recruiting': 356, 'Browser Extensions': 343, 'Human Resources': 343, 'Email Marketing': 333, 'Social Media Marketing': 320, 'Chat': 301, 'Freelancers': 285, 'Designers': 285, 'Content Creators': 275, 'Product Design': 274, 'Finance Technology': 268, 'Web Hosting': 266, 'Lead Generation': 255, 'iOS': 255, 'SEO': 238, 'New Product Development': 237, 'Finance': 236, 'Databases': 233, 'Machine Learning': 229, 'Business Analytics': 227, 'Customer Service': 226, 'AI Image Creation': 217, 'Data Integration': 216, 'Tracking': 215, 'Communities': 213, 'Video': 212, 'Remote Work': 201, 'Brand Marketing': 197, 'User Testing': 197, 'Business Intelligence': 191, 'Legal': 186, 'Task Management': 184, 'Marketplaces': 180, 'Document Management': 169, 'Data Visualization': 166, 'Private Social Networking': 165, 'Application Performance Monitoring': 162, 'Cryptocurrencies': 160, 'Business Development': 157, 'Mobile Social': 157, 'Email Newsletters': 155, 'Market Research': 154, 'Blockchain': 153, 'Blogging Platforms': 152, 'Feedback Tools': 152, 'Entrepreneur': 151, 'Domains': 148, 'Human Resource Automation': 147, 'Security': 145, 'Health and Wellness': 139, 'Presentations': 137, 'Content': 136, 'Cloud Data Services': 133, 'Bots': 133, 'Graphics': 130, 'Messaging': 128, 'AI Marketing': 124, 'Meeting Software': 124, 'Lead Management': 119, 'Career Planning': 117, 'Video Editing': 115, 'Cloud Computing': 113, 'Cloud Infrastructure': 112, 'Information Technology': 109, 'Privacy': 108, 'Search Marketing': 105, 'Career Management': 105, 'Knowledge Management': 103, 'Cyber Security': 101, 'AI Assistant': 101, 'Performance Marketing': 100, 'Lifestyle': 100, 'Payments': 100}

In [ ]:
print(revised_topic_count.items())

dict_items([('Blogging Platforms', 152), ('Performance Marketing', 100), ('SEO', 238), ('SaaS', 13137), ('B2B', 1118), ('Freelancers', 285), ('Lifestyle', 100), ('Analytics', 1320), ('Task Management', 184), ('Productivity Software', 4966), ('Business Productivity', 3805), ('Application Performance Monitoring', 162), ('Education', 709), ('Health and Wellness', 139), ('Video', 212), ('Artificial Intelligence', 1399), ('Web Tools', 5870), ('AI Tools', 681), ('Feedback Tools', 152), ('Document Management', 169), ('User Experience Design', 399), ('Developer Tools', 5698), ('Web Development', 4178), ('Web Design', 1511), ('Email Newsletters', 155), ('Design', 804), ('No Code', 409), ('Social Media Marketing', 320), ('E-Commerce', 848), ('Collaboration', 1093), ('Web CMS', 372), ('Email Marketing', 333), ('Brand Marketing', 197), ('Web Hosting', 266), ('Domains', 148), ('Designers', 285), ('Graphics', 130), ('Data Visualization', 166), ('Business Services', 525), ('Mobile', 888), ('Startups', 7295), ('Marketplaces', 180), ('User Testing', 197), ('Developer APIs', 881), ('AI Chat', 443), ('AI Image Creation', 217), ('Business Development', 157), ('Market Research', 154), ('Apps', 1268), ('Tracking', 215), ('Browser Extensions', 343), ('AI Marketing', 124), ('Small and Medium Businesses', 2205), ('Internet Marketing', 1049), ('Social Media', 843), ('Email', 374), ('Product Design', 274), ('Communities', 213), ('Software', 790), ('Development Platforms', 820), ('Sales and Marketing', 1824), ('Customer Support Tools', 400), ('Marketing Automation', 494), ('Content Creators', 275), ('Cloud Computing', 113), ('Cyber Security', 101), ('New Product Development', 237), ('Project Management', 638), ('Sales Automation', 748), ('Content', 136), ('Search Marketing', 105), ('Lead Management', 119), ('Lead Generation', 255), ('iOS', 255), ('Business Analytics', 227), ('Cloud Data Services', 133), ('Entrepreneur', 151), ('CRM', 448), ('Career Planning', 117), ('Machine Learning', 229), ('Customer Service', 226), ('Recruiting', 356), ('Chat', 301), ('Presentations', 137), ('Human Resource Automation', 147), ('Information Technology', 109), ('Payments', 100), ('Cloud Infrastructure', 112), ('Security', 145), ('Private Social Networking', 165), ('Business Intelligence', 191), ('Enterprise Software', 478), ('Technology', 620), ('Knowledge Management', 103), ('Human Resources', 343), ('Finance', 236), ('Data Integration', 216), ('Privacy', 108), ('Legal', 186), ('Finance Technology', 268), ('Meeting Software', 124), ('Mobile Social', 157), ('Remote Work', 201), ('Blockchain', 153), ('Video Editing', 115), ('Messaging', 128), ('Bots', 133), ('AI Assistant', 101), ('Cryptocurrencies', 160), ('Career Management', 105), ('Databases', 233)])

In [ ]:
encode_topics_types = {key: idx for idx, (key, value) in enumerate(revised_topic_count.items())}
with open("topic_encoded.json", "w") as fp:
  json.dump(encode_topics_types, fp)

In [ ]:
len(encode_topics_types)

111

In [ ]:
# We need this because for multilabel classification all topics have possibility to be present in the predictions
categorical_topic_list = []
revised_topics_list = df.topics.to_list()

for revised_topics in revised_topics_list:
  categorical_list = [0] * len(encode_topics_types)
  for topic in revised_topics:
    topic_type_index = encode_topics_types[topic]
    categorical_list[topic_type_index] = 1
  categorical_topic_list.append(categorical_list)

In [ ]:
#print(categorical_topic_list[20000])

In [ ]:
df['topic_category'] = categorical_topic_list

In [ ]:
#df.drop(columns=('topic_category_list'), axis=1)

In [ ]:
df.head()

,name,motto,description,topics,url,topic_category
0,Flux Plugins,"Speed up WordPress with AI-powered image, SEO,...",Flux Plugins provides a suite of WordPress plu...,"[Blogging Platforms, Performance Marketing, SEO]",https://betalist.com/startups/flux-plugins,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,Wafaa.io BOOSTED,Create digital contracts in minutes,Wafaa is your new one-stop shop for digital co...,"[SaaS, B2B, Freelancers]",https://betalist.com/startups/wafaa-io,"[0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,Vaulternal,Store and automate file access with secure fil...,"Vaulternal offers encrypted, decentralized fil...","[Lifestyle, SaaS]",https://betalist.com/startups/vaulternal,"[0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,PUBVOICE,Turn your articles into audio and boost reader...,PUBVOICE converts your articles into high-qual...,[Analytics],https://betalist.com/startups/pubvoice,"[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ..."
4,OPT-IMG,"AI tool to optimize images for SEO, speed, and...",OPT-IMG is an AI-powered image SEO platform th...,[SEO],https://betalist.com/startups/opt-img,"[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [ ]:
#df.to_csv("NLP_Preprocessed_Dataset.csv", index=False)