# Setup & Dependencies

In [ ]:
#%matplotlib inline

In [ ]:
! pip install -q transformers[sentencepiece] fastbook fastai nbdev plum-dispatch evaluate seqeval onnxruntime onnx

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 2.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 719.8/719.8 kB 23.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.0/76.0 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 9.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.7/18.7 MB 95.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 104.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.4/71.4 kB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 127.0 MB/s eta 0:00:00
  Building wheel for seqeval (setup.py) ... done

In [ ]:
!pip install -q onnxscript

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 714.8/714.8 kB 11.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.8/166.8 kB 7.8 MB/s eta 0:00:00

In [ ]:
!git clone https://github.com/msi1427/blurr.git
%cd blurr

Cloning into 'blurr'...
remote: Enumerating objects: 5063, done.
remote: Counting objects: 100% (890/890), done.
remote: Compressing objects: 100% (310/310), done.
remote: Total 5063 (delta 701), reused 699 (delta 573), pack-reused 4173 (from 1)
Receiving objects: 100% (5063/5063), 27.00 MiB | 21.58 MiB/s, done.
Resolving deltas: 100% (3932/3932), done.
/content/blurr

In [ ]:
import torch
from transformers import AutoModelForSequenceClassification, AutoConfig
from fastai.text.all import *
from blurr.text.data.all import *
from blurr.text.modeling.all import *

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

In [ ]:
from tqdm.notebook import tqdm
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
%cd "/content/drive/MyDrive/Startups_Recognize"

/content/drive/MyDrive/Startups_Recognize

In [ ]:
#DATA_PATH = '/content/drive/MyDrive/Startups_Recognize/NLP_Preprocessed_Dataset.csv'
df = pd.read_csv('NLP_Preprocessed_Dataset.csv')

In [ ]:
df.head()

,name,motto,description,topics,url,topic_category
0,Flux Plugins,"Speed up WordPress with AI-powered image, SEO, and accessibility tools","Flux Plugins provides a suite of WordPress plugins that boost speed, accessibility, and SEO. The Flux Suite includes Media Optimizer for compressing and serving images efficiently and AI Alt Text & Accessibility Audit to generate alt text and flag issues affecting compliance. Install in minutes, reduce bandwidth, and keep visitors engaged with faster, more accessible pages.","['Blogging Platforms', 'Performance Marketing', 'SEO']",https://betalist.com/startups/flux-plugins,"[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
1,Wafaa.io BOOSTED,Create digital contracts in minutes,"Wafaa is your new one-stop shop for digital contracts. Create, sign, and send contracts in minutes so you can get back to work. Replace scattered and unsecured agreements across platforms and manage the full contract lifecycle at a glance. Protect your money and time with built-in fraud prevention, and skip the subscriptions by paying as you go. Try before you buy: your first contract is on us.","['SaaS', 'B2B', 'Freelancers']",https://betalist.com/startups/wafaa-io,"[0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
2,Vaulternal,Store and automate file access with secure file storage,"Vaulternal offers encrypted, decentralized file storage with zero-knowledge privacy and smart triggers. Files are encrypted client-side and stored across multiple decentralized blockchains, including Polygon, removing single points of failure and preventing provider access. You can set time-based, inactivity, manual, or blockchain-event conditions to deliver files to chosen recipients, enabling controlled sharing and inheritance. Sign up with email or connect a wallet, manage multiple recipients, and rely on verifiable permanence and client-side decryption.","['Lifestyle', 'SaaS']",https://betalist.com/startups/vaulternal,"[0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
3,PUBVOICE,Turn your articles into audio and boost reader engagement,"PUBVOICE converts your articles into high-quality audio and delivers it through an embeddable player. Connect your RSS feed to auto-detect new posts, let AI generate listener-friendly scripts, and choose from 30 adjustable voices. Control creation, delivery, and performance from a single dashboard with metrics like plays, dwell time, and completion rate. Customize the player with CSS, clone voices, and keep content private from AI training. Implementation takes minutes with a lightweight script tag, and early access grants all features for free.",['Analytics'],https://betalist.com/startups/pubvoice,"[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
4,OPT-IMG,"AI tool to optimize images for SEO, speed, and scale automatically","OPT-IMG is an AI-powered image SEO platform that turns raw images into SEO-ready, faster-loading assets. It automatically generates SEO-friendly filenames and alt text and compresses images in a single workflow. Users can batch process images, create responsive outputs, and export optimized assets at scale. OPT-IMG helps improve image search visibility, page speed, and Core Web Vitals for eCommerce sites, blogs, and content teams.",['SEO'],https://betalist.com/startups/opt-img,"[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"

# Encoding Data

In [ ]:
print(df.topics[0])

['Blogging Platforms', 'Performance Marketing', 'SEO']

In [ ]:
type(df.topics[0])

str

In [ ]:
list_category = df.topics.to_list()
encode_count = {}

for topics in list_category:
  topics = topics.replace("[", "").replace("'", "").replace("]", "")
  topics_list = topics.split(",")
  for topic in topics_list:
    topic = topic.strip()
    if topic in encode_count.keys():
      encode_count[topic] += 1
    else:
      encode_count[topic] = 1

In [ ]:
#print(encode_count)

In [ ]:
encode_topic_types = {key: idx for idx, (key, value) in enumerate(encode_count.items())}

In [ ]:
#encode_topic_types

In [ ]:
labels = list(encode_topic_types.keys())
len(labels), labels[:5]

(111, ['Blogging Platforms', 'Performance Marketing', 'SEO', 'SaaS', 'B2B'])

# Splitting of Datasets

In [ ]:
splitter = RandomSplitter(valid_pct=0.1, seed=42)
train_ids, valid_ids = splitter(df)
len(train_ids), len(valid_ids)

(19218, 2135)

In [ ]:
valid_df = df.loc[valid_ids]
valid_df.head()

,name,motto,description,topics,url,topic_category
9287,10X,Build a community on your website,"10X enables anyone to add an engaging social interface to their website with one line of code. Returning more frequently to find fresh and interesting content promotes brand loyalty, peer to peer marketing, and on-site conversions.","['Brand Marketing', 'Web Tools', 'Social Media Marketing']",https://betalist.com/startups/10x,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
1868,Bpzoo,Free professional graphics & online coloring platform,"Bpzoo is your free online graphics provider - powered by a basic color tool. We offer thousands of free and premium vector graphics on our platform, for both commercial and personal use.","['Design', 'Web Design', 'Graphics']",https://betalist.com/startups/bpzoo,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
14883,Internal,Monitor you and your team's well-being,Internal is a Slack bot that facilitates emotional communication for remote teams. All users take twice daily questionnaires to check in at the start of the day and reflect at the end of their day. Individual check in overall scores are reported to a public channel so that coworkers gather the same emotional insights that they would from body language in a physical setting. Reflections are used to track personal emotional fitness overtime.,"['SaaS', 'Business Productivity', 'Analytics']",https://betalist.com/startups/internal,"[0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
10067,fileGOD,Process PDFs and images in your browser without uploading,"fileGOD provides fast browser-based tools for PDFs and images that keep files on your device. You can compress, convert, merge, split, resize, crop, watermark, and more without uploading, protecting your privacy. It offers over 30 utilities including PDF to JPG, HEIC to JPG, OCR, and ZIP create/extract, supporting files up to 2GB. Start free with weekly actions and upgrade for heavier use.","['Document Management', 'Productivity Software', 'Business Productivity', 'Web Tools', 'SaaS']",https://betalist.com/startups/filegod,"[0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"
14941,Narrowr,Share one link per day - Build a feed you enjoy - Discover great content,"Narrowr is a social link-sharing platform that puts users first. We want people to think about what they share, opposed to mindlessly putting everything out there. Every member gets to share only one link per day – This constraint aims to promote quality over quantity and make feeds less addictive by nature. No algorithms, no ads, no tracking. It's all about our members and the content they enjoy.","['SaaS', 'Social Media']",https://betalist.com/startups/narrowr,"[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]"

# Fastai & Blurr model load

In [ ]:
model_path = "models-roberta-base/book-roberta-base-classifier-stage-1.pkl"
learner_inf = load_learner(model_path)

In [ ]:
learner_inf.blurr_predict("random placeholder")

[{'labels': ['Web Tools', 'Web Development'],
  'scores': [0.8566012978553772, 0.8267977237701416],
  'class_indices': [0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   1,
   0,
   0,
   0,
   0,
   0,
   1,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0],
  'class_labels': ['Blogging Platforms', 'Performance Marketing', 'SEO', 'SaaS', 'B2B', 'Freelancers', 'Lifestyle', 'Analytics', 'Task Management', 'Productivity Software', 'Business Productivity', 'Application Performance Monitoring', 'Education', 'Health and Wellness', 'Video', 'Artificial Intelligence', 'Web Tools', 'AI Tools', 'Feedback Tools', 'Document Management', 'User Experience Design', 'Developer Tools', 'Web Development', 'Web Design', 'Email Newsletters', 'Design', 'No Code', 'Social Media Marketing', 'E-Commerce', 'Collaboration', 'Web CMS', 'Email Marketing', 'Brand Marketing', 'Web Hosting', 'Domains', 'Designers', 'Graphics', 'Data Visualization', 'Business Services', 'Mobile', 'Startups', 'Marketplaces', 'User Testing', 'Developer APIs', 'AI Chat', 'AI Image Creation', 'Business Development', 'Market Research', 'Apps', 'Tracking', 'Browser Extensions', 'AI Marketing', 'Small and Medium Businesses', 'Internet Marketing', 'Social Media', 'Email', 'Product Design', 'Communities', 'Software', 'Development Platforms', 'Sales and Marketing', 'Customer Support Tools', 'Marketing Automation', 'Content Creators', 'Cloud Computing', 'Cyber Security', 'New Product Development', 'Project Management', 'Sales Automation', 'Content', 'Search Marketing', 'Lead Management', 'Lead Generation', 'iOS', 'Business Analytics', 'Cloud Data Services', 'Entrepreneur', 'CRM', 'Career Planning', 'Machine Learning', 'Customer Service', 'Recruiting', 'Chat', 'Presentations', 'Human Resource Automation', 'Information Technology', 'Payments', 'Cloud Infrastructure', 'Security', 'Private Social Networking', 'Business Intelligence', 'Enterprise Software', 'Technology', 'Knowledge Management', 'Human Resources', 'Finance', 'Data Integration', 'Privacy', 'Legal', 'Finance Technology', 'Meeting Software', 'Mobile Social', 'Remote Work', 'Blockchain', 'Video Editing', 'Messaging', 'Bots', 'AI Assistant', 'Cryptocurrencies', 'Career Management', 'Databases'],
  'probs': [0.009557977318763733,
   0.0013533945893868804,
   0.011436372995376587,
   0.08913953602313995,
   0.006051266565918922,
   0.0041344002820551395,
   0.0023351714480668306,
   0.005539938807487488,
   0.00178437028080225,
   0.3928048610687256,
   0.025426074862480164,
   0.0025697664823383093,
   0.009361027739942074,
   0.0011900856625288725,
   0.0029087739530950785,
   0.006263562478125095,
   0.8566012978553772,
   0.004410149063915014,
   0.0011534607037901878,
   0.002260705456137657,
   0.01313245203346014,
   0.12679564952850342,
   0.8267977237701416,
   0.4699864685535431,
   0.003244612365961075,
   0.0424467958509922,
   0.00878998264670372,
   0.004212660249322653,
   0.007488827221095562,
   0.009324400685727596,
   0.06413454562425613,
   0.002174816094338894,
   0.003330506384372711,
   0.011090099811553955,
   0.003990922588855028,
   0.014885401353240013,
   0.0035707857459783554,
   0.0016894314903765917,
   0.004880023654550314,
   0.004805075936019421,
   0.06550111621618271,
   0.0038042536471039057,
   0.002553406869992614,
   0.005469904746860266,
   0.0027035085950046778,
   0.0031992048025131226,
   0.0029702698811888695,
   0.002120264805853367,
   0.015454770065844059,
   0.0015399577096104622,
   0.019163526594638824,
   0.0009968607919290662,
   0.011522950604557991,
   0.036192700266838074,
   0.009369556792080402,
   0.002795425010845065,
   0.015929248183965683,
   0.0020882654935121536,
   0.010682741180062294,
   0.006820807699114084,
   0.011907434090971947,
   0.00145603041164577,
   0.003761548548936844,
   0.006738654337823391,
   0.0016476238379254937,
   0.0010702712461352348,
   0.004790006671100855,
   0.0044079991057515144,
   0.0015167278470471501,
   0.004025985021144152,
   0.003410063683986664,
   0.0008641128079034388,
   0.0011487735901027918,
   0.0025872900150716305,
   0.001101836794987321,
   0.0019386009080335498,
   0.003110964549705386,
   0.0013881702907383442,
   0.0023184337187558413,
   0.0029652975499629974,
   0.0007137450156733394,
   0.0026958133094012737,
   0.0015049349749460816,
   0.0036261999048292637,
   0.0008776367176324129,
   0.001449539209716022,
   0.0006891716620884836,
   0.0012035273248329759,
   0.002154748421162367,
   0.0019868474919348955,
   0.001391880796290934,
   0.0023251804523169994,
   0.004654217511415482,
   0.0011865744600072503,
   0.0013149067526683211,
   0.001317654736340046,
   0.0014462900580838323,
   0.001550763612613082,
   0.0006527095101773739,
   0.0006307400763034821,
   0.0007746912306174636,
   0.0015978873707354069,
   0.0017981474520638585,
   0.0006492819520644844,
   0.0018127054208889604,
   0.0012362053385004401,
   0.0010106295812875032,
   0.0007549378788098693,
   0.0009119357564486563,
   0.0025490240659564734,
   0.0025263652205467224]}]

In [ ]:
learner_inf.blurr_predict("random placeholder")[0]['labels']

['Web Tools', 'Web Development']

## Evaluation Metrics

In [ ]:
from sklearn import metrics

In [ ]:
def metric_measures(test_df, preds):

  targets = [np.asarray(target) for target in test_df['topic_category'].to_list()]
  outputs = [np.asarray(pred) for pred in preds]


  accuracy = metrics.accuracy_score(targets, outputs)
  f1_score_micro = metrics.f1_score(targets, outputs, average='micro')
  f1_score_macro = metrics.f1_score(targets, outputs, average='macro')

  print(f"F1 Score (Micro) = {f1_score_micro}")
  print(f"F1 Score (Macro) = {f1_score_macro}")

  return

In [ ]:
preds = []
for idx, row in tqdm(valid_df.iterrows(), total=len(valid_df)):
  desc = row['description']
  labels = learner_inf.blurr_predict(desc)[0]['class_indices']
  # pred_genres = [0] * len(encode_genre_types)
  # for label in labels:
  #   pred_genres[encode_genre_types[label]] = 1
  preds.append(labels)

preds[0][:20]

  0%|          | 0/2135 [00:00<?, ?it/s]

[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [ ]:
import ast

In [ ]:
# Create a copy to avoid modifying the original valid_df if it's used elsewhere
valid_df_processed = valid_df.copy()
# Convert the 'topic_category' column from string representation of lists to actual lists
valid_df_processed['topic_category'] = valid_df_processed['topic_category'].apply(ast.literal_eval)

metric_measures(valid_df_processed, preds)

F1 Score (Micro) = 0.7590176002141471
F1 Score (Macro) = 0.2934824248575889

# Convert fastai & blurr model to ONNX

In [ ]:
model_path = "models-roberta-base/book-roberta-base-classifier-stage-1.pkl"
learner_inf = load_learner(model_path)

In [ ]:
learner_inf.model.hf_model

RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0-11): 12 x RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): RobertaIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): RobertaOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
  )
  (classifier): RobertaClassificationHead(
    (dense): Linear(in_features=768, out_features=768, bias=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (out_proj): Linear(in_features=768, out_features=111, bias=True)
  )
)

In [ ]:
classifier = learner_inf.model.hf_model.eval()

torch.onnx.export(
    classifier,
    torch.LongTensor([[0] * 512])
    'models/book-classifier.onnx',
    verbose=True,
    input_names=['input_ids', 'attention_mask'],
    output_names=['output'],
    opset_version=18,
    dynamic_axes={
        'input_ids': {0: 'batch_size', 1: 'sequence_len'},
        'attention_mask': {0: 'batch_size', 1: 'sequence_len'},
        'output': {0: 'batch_size'}
    }
)

[torch.onnx] Obtain model graph for `RobertaForSequenceClassification([...]` with `torch.export.export(..., strict=False)`...
[torch.onnx] Obtain model graph for `RobertaForSequenceClassification([...]` with `torch.export.export(..., strict=False)`... ✅
[torch.onnx] Run decompositions...
[torch.onnx] Run decompositions... ✅
[torch.onnx] Translate the graph into ONNX...
[torch.onnx] Translate the graph into ONNX... ✅
[torch.onnx] Optimize the ONNX graph...
[torch.onnx] Optimize the ONNX graph... ✅

ONNXProgram(
    model=
        <
            ir_version=10,
            opset_imports={'': 18},
            producer_name='pytorch',
            producer_version='2.11.0+cu128',
            domain=None,
            model_version=None,
        >
        graph(
            name=main_graph,
            inputs=(
                %"input_ids"<INT64,[batch_size,sequence_len]>,
                %"attention_mask"<INT64,[batch_size,sequence_len]>
            ),
            outputs=(
                %"output"<FLOAT,[1,111]>
            ),
            initializers=(
                %"roberta.embeddings.word_embeddings.weight"<FLOAT,[50265,768]>{TorchTensor(...)},
                %"roberta.embeddings.token_type_embeddings.weight"<FLOAT,[1,768]>{TorchTensor(...)},
                %"roberta.embeddings.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.embeddings.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.embeddings.position_embeddings.weight"<FLOAT,[514,768]>{TorchTensor(...)},
                %"roberta.encoder.layer.0.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.0.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.0.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.0.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.0.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.0.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.0.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.0.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.0.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.0.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.1.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.1.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.1.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.1.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.1.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.1.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.1.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.1.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.1.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.1.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.2.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.2.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.2.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.2.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.2.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.2.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.2.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.2.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.2.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.2.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.3.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.3.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.3.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.3.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.3.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.3.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.3.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.3.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.3.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.3.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.4.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.4.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.4.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.4.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.4.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.4.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.4.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.4.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.4.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.4.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.5.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.5.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.5.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.5.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.5.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.5.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.5.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.5.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.5.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.5.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.6.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.6.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.6.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.6.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.6.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.6.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.6.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.6.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.6.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.6.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.7.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.7.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.7.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.7.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.7.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.7.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.7.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.7.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.7.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.7.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.8.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.8.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.8.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.8.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.8.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.8.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.8.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.8.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.8.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.8.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.9.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.9.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.9.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.9.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.9.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.9.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.9.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.9.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.9.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.9.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.10.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.10.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.10.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.10.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.10.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.10.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.10.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.10.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.10.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.10.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.11.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.11.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.11.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.11.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.11.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.11.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.11.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.11.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.11.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.11.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"classifier.dense.weight"<FLOAT,[768,768]>{TorchTensor(...)},
                %"classifier.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"classifier.out_proj.weight"<FLOAT,[111,768]>{TorchTensor(...)},
                %"classifier.out_proj.bias"<FLOAT,[111]>{TorchTensor(...)},
                %"roberta.embeddings.token_type_ids"<INT64,[1,514]>{TorchTensor(...)},
                %"val_20"<INT64,[]>{Tensor<INT64,[]>(array(0), name='val_20')},
                %"val_22"<INT64,[]>{Tensor<INT64,[]>(array(1), name='val_22')},
                %"new_ones"<BOOL,[]>{Tensor<BOOL,[]>(array(True), name='new_ones')},
                %"val_83"<FLOAT,[768,768]>{Tensor(...)},
                %"val_91"<FLOAT,[768,768]>{Tensor(...)},
                %"val_99"<FLOAT,[768,768]>{Tensor(...)},
                %"val_122"<FLOAT,[]>{Tensor<FLOAT,[]>(array(0.35355338, dtype=float32), name='val_122')},
                %"val_139"<FLOAT,[768,768]>{Tensor(...)},
                %"val_143"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_152"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_156"<FLOAT,[768,768]>{Tensor(...)},
                %"val_164"<FLOAT,[768,768]>{Tensor(...)},
                %"val_172"<FLOAT,[768,768]>{Tensor(...)},
                %"val_210"<FLOAT,[768,768]>{Tensor(...)},
                %"val_214"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_223"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_227"<FLOAT,[768,768]>{Tensor(...)},
                %"val_235"<FLOAT,[768,768]>{Tensor(...)},
                %"val_243"<FLOAT,[768,768]>{Tensor(...)},
                %"val_281"<FLOAT,[768,768]>{Tensor(...)},
                %"val_285"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_294"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_298"<FLOAT,[768,768]>{Tensor(...)},
                %"val_306"<FLOAT,[768,768]>{Tensor(...)},
                %"val_314"<FLOAT,[768,768]>{Tensor(...)},
                %"val_352"<FLOAT,[768,768]>{Tensor(...)},
                %"val_356"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_365"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_369"<FLOAT,[768,768]>{Tensor(...)},
                %"val_377"<FLOAT,[768,768]>{Tensor(...)},
                %"val_385"<FLOAT,[768,768]>{Tensor(...)},
                %"val_423"<FLOAT,[768,768]>{Tensor(...)},
                %"val_427"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_436"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_440"<FLOAT,[768,768]>{Tensor(...)},
                %"val_448"<FLOAT,[768,768]>{Tensor(...)},
                %"val_456"<FLOAT,[768,768]>{Tensor(...)},
                %"val_494"<FLOAT,[768,768]>{Tensor(...)},
                %"val_498"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_507"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_511"<FLOAT,[768,768]>{Tensor(...)},
                %"val_519"<FLOAT,[768,768]>{Tensor(...)},
                %"val_527"<FLOAT,[768,768]>{Tensor(...)},
                %"val_565"<FLOAT,[768,768]>{Tensor(...)},
                %"val_569"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_578"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_582"<FLOAT,[768,768]>{Tensor(...)},
                %"val_590"<FLOAT,[768,768]>{Tensor(...)},
                %"val_598"<FLOAT,[768,768]>{Tensor(...)},
                %"val_636"<FLOAT,[768,768]>{Tensor(...)},
                %"val_640"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_649"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_653"<FLOAT,[768,768]>{Tensor(...)},
                %"val_661"<FLOAT,[768,768]>{Tensor(...)},
                %"val_669"<FLOAT,[768,768]>{Tensor(...)},
                %"val_707"<FLOAT,[768,768]>{Tensor(...)},
                %"val_711"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_720"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_724"<FLOAT,[768,768]>{Tensor(...)},
                %"val_732"<FLOAT,[768,768]>{Tensor(...)},
                %"val_740"<FLOAT,[768,768]>{Tensor(...)},
                %"val_778"<FLOAT,[768,768]>{Tensor(...)},
                %"val_782"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_791"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_795"<FLOAT,[768,768]>{Tensor(...)},
                %"val_803"<FLOAT,[768,768]>{Tensor(...)},
                %"val_811"<FLOAT,[768,768]>{Tensor(...)},
                %"val_849"<FLOAT,[768,768]>{Tensor(...)},
                %"val_853"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_862"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_866"<FLOAT,[768,768]>{Tensor(...)},
                %"val_874"<FLOAT,[768,768]>{Tensor(...)},
                %"val_882"<FLOAT,[768,768]>{Tensor(...)},
                %"val_920"<FLOAT,[768,768]>{Tensor(...)},
                %"val_924"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_933"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_10"<INT64,[1]>{Tensor<INT64,[1]>(array([1]), name='val_10')},
                %"val_39"<INT64,[1]>{Tensor<INT64,[1]>(array([2]), name='val_39')},
                %"val_937"<INT64,[2]>{Tensor<INT64,[2]>(array([1, 2]), name='val_937')},
                %"val_40"<INT64,[1]>{Tensor<INT64,[1]>(array([3]), name='val_40')},
                %"val_938"<INT64,[2]>{Tensor<INT64,[2]>(array([0, 1]), name='val_938')},
                %"val_71"<INT64,[1]>{Tensor<INT64,[1]>(array([-1]), name='val_71')},
                %"val_89"<INT64,[1]>{Tensor<INT64,[1]>(array([64]), name='val_89')},
                %"val_110"<INT64,[1]>{Tensor<INT64,[1]>(array([9223372036854775807]), name='val_110')},
                %"val_112"<INT64,[1]>{Tensor<INT64,[1]>(array([-2]), name='val_112')},
                %"val_114"<INT64,[1]>{Tensor<INT64,[1]>(array([-9223372036854775808]), name='val_114')},
                %"val_126"<FLOAT,[]>{Tensor<FLOAT,[]>(array(0., dtype=float32), name='val_126')},
                %"val_127"<FLOAT,[]>{Tensor<FLOAT,[]>(array(-3.4028235e+38, dtype=float32), name='val_127')},
                %"val_145"<FLOAT,[]>{Tensor<FLOAT,[]>(array(1.4142135, dtype=float32), name='val_145')},
                %"val_148"<FLOAT,[]>{Tensor<FLOAT,[]>(array(1., dtype=float32), name='val_148')},
                %"val_150"<FLOAT,[]>{Tensor<FLOAT,[]>(array(0.5, dtype=float32), name='val_150')}
            ),
        ) {
              0 |  # node_Shape_0
                   %"val_0"<INT64,[1]> ⬅️ ::Shape(%"input_ids") {end=1, start=0}
              1 |  # node_sym_size_int_15
                   %"sym_size_int_15"<INT64,[]> ⬅️ ::Squeeze(%"val_0")
              2 |  # node_Shape_1
                   %"val_1"<INT64,[1]> ⬅️ ::Shape(%"attention_mask") {end=2, start=1}
              3 |  # node_sym_size_int_18
                   %"sym_size_int_18"<INT64,[]> ⬅️ ::Squeeze(%"val_1")

In [ ]:
from onnxruntime.quantization import quantize_dynamic, QuantType

In [ ]:
#onnx_model_path = 'models/book-classifier.onnx'
#quantized_onnx_model_path = 'models/book-classifier-quantized.onnx'

#quantize_dynamic(
#    onnx_model_path,
 #   quantized_onnx_model_path,
#    weight_type=QuantType.QUInt8,
#)

WARNING:root:Please consider to run pre-processing before quantization. Refer to example: https://github.com/microsoft/onnxruntime-inference-examples/blob/main/quantization/image_classification/cpu/ReadMe.md

InferenceError: [ShapeInferenceError] Inferred shape and existing shape differ in dimension 0: (768) vs (111)

In [ ]:
dummy_input_ids = torch.LongTensor([[0] * 512])
dummy_attention_mask = torch.ones(1, 512, dtype=torch.long)

torch.onnx.export(
    classifier,
    (dummy_input_ids, dummy_attention_mask),   # tuple not single tensor
    'models/book-classifier.onnx',
    input_names=['input_ids', 'attention_mask'],
    output_names=['output'],
    opset_version=18,
    dynamic_axes={
        'input_ids': {0: 'batch_size', 1: 'sequence_len'},
        'attention_mask': {0: 'batch_size', 1: 'sequence_len'},
        'output': {0: 'batch_size'}
    }
)

[torch.onnx] Obtain model graph for `RobertaForSequenceClassification([...]` with `torch.export.export(..., strict=False)`...
[torch.onnx] Obtain model graph for `RobertaForSequenceClassification([...]` with `torch.export.export(..., strict=False)`... ✅
[torch.onnx] Run decompositions...
[torch.onnx] Run decompositions... ✅
[torch.onnx] Translate the graph into ONNX...
[torch.onnx] Translate the graph into ONNX... ✅
[torch.onnx] Optimize the ONNX graph...
[torch.onnx] Optimize the ONNX graph... ✅

ONNXProgram(
    model=
        <
            ir_version=10,
            opset_imports={'': 18},
            producer_name='pytorch',
            producer_version='2.11.0+cu128',
            domain=None,
            model_version=None,
        >
        graph(
            name=main_graph,
            inputs=(
                %"input_ids"<INT64,[batch_size,sequence_len]>,
                %"attention_mask"<INT64,[batch_size,sequence_len]>
            ),
            outputs=(
                %"output"<FLOAT,[1,111]>
            ),
            initializers=(
                %"roberta.embeddings.word_embeddings.weight"<FLOAT,[50265,768]>{TorchTensor(...)},
                %"roberta.embeddings.token_type_embeddings.weight"<FLOAT,[1,768]>{TorchTensor(...)},
                %"roberta.embeddings.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.embeddings.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.embeddings.position_embeddings.weight"<FLOAT,[514,768]>{TorchTensor(...)},
                %"roberta.encoder.layer.0.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.0.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.0.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.0.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.0.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.0.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.0.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.0.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.0.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.0.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.1.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.1.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.1.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.1.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.1.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.1.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.1.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.1.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.1.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.1.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.2.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.2.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.2.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.2.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.2.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.2.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.2.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.2.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.2.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.2.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.3.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.3.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.3.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.3.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.3.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.3.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.3.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.3.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.3.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.3.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.4.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.4.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.4.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.4.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.4.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.4.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.4.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.4.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.4.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.4.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.5.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.5.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.5.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.5.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.5.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.5.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.5.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.5.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.5.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.5.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.6.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.6.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.6.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.6.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.6.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.6.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.6.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.6.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.6.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.6.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.7.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.7.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.7.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.7.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.7.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.7.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.7.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.7.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.7.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.7.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.8.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.8.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.8.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.8.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.8.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.8.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.8.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.8.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.8.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.8.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.9.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.9.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.9.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.9.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.9.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.9.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.9.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.9.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.9.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.9.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.10.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.10.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.10.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.10.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.10.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.10.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.10.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.10.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.10.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.10.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.11.attention.self.query.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.11.attention.self.key.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.11.attention.self.value.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.11.attention.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.11.attention.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.11.attention.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.11.intermediate.dense.bias"<FLOAT,[3072]>{TorchTensor(...)},
                %"roberta.encoder.layer.11.output.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.11.output.LayerNorm.weight"<FLOAT,[768]>{TorchTensor(...)},
                %"roberta.encoder.layer.11.output.LayerNorm.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"classifier.dense.weight"<FLOAT,[768,768]>{TorchTensor(...)},
                %"classifier.dense.bias"<FLOAT,[768]>{TorchTensor(...)},
                %"classifier.out_proj.weight"<FLOAT,[111,768]>{TorchTensor(...)},
                %"classifier.out_proj.bias"<FLOAT,[111]>{TorchTensor(...)},
                %"roberta.embeddings.token_type_ids"<INT64,[1,514]>{TorchTensor(...)},
                %"val_20"<INT64,[]>{Tensor<INT64,[]>(array(0), name='val_20')},
                %"val_22"<INT64,[]>{Tensor<INT64,[]>(array(1), name='val_22')},
                %"new_ones"<BOOL,[]>{Tensor<BOOL,[]>(array(True), name='new_ones')},
                %"val_83"<FLOAT,[768,768]>{Tensor(...)},
                %"val_91"<FLOAT,[768,768]>{Tensor(...)},
                %"val_99"<FLOAT,[768,768]>{Tensor(...)},
                %"val_122"<FLOAT,[]>{Tensor<FLOAT,[]>(array(0.35355338, dtype=float32), name='val_122')},
                %"val_139"<FLOAT,[768,768]>{Tensor(...)},
                %"val_143"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_152"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_156"<FLOAT,[768,768]>{Tensor(...)},
                %"val_164"<FLOAT,[768,768]>{Tensor(...)},
                %"val_172"<FLOAT,[768,768]>{Tensor(...)},
                %"val_210"<FLOAT,[768,768]>{Tensor(...)},
                %"val_214"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_223"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_227"<FLOAT,[768,768]>{Tensor(...)},
                %"val_235"<FLOAT,[768,768]>{Tensor(...)},
                %"val_243"<FLOAT,[768,768]>{Tensor(...)},
                %"val_281"<FLOAT,[768,768]>{Tensor(...)},
                %"val_285"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_294"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_298"<FLOAT,[768,768]>{Tensor(...)},
                %"val_306"<FLOAT,[768,768]>{Tensor(...)},
                %"val_314"<FLOAT,[768,768]>{Tensor(...)},
                %"val_352"<FLOAT,[768,768]>{Tensor(...)},
                %"val_356"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_365"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_369"<FLOAT,[768,768]>{Tensor(...)},
                %"val_377"<FLOAT,[768,768]>{Tensor(...)},
                %"val_385"<FLOAT,[768,768]>{Tensor(...)},
                %"val_423"<FLOAT,[768,768]>{Tensor(...)},
                %"val_427"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_436"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_440"<FLOAT,[768,768]>{Tensor(...)},
                %"val_448"<FLOAT,[768,768]>{Tensor(...)},
                %"val_456"<FLOAT,[768,768]>{Tensor(...)},
                %"val_494"<FLOAT,[768,768]>{Tensor(...)},
                %"val_498"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_507"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_511"<FLOAT,[768,768]>{Tensor(...)},
                %"val_519"<FLOAT,[768,768]>{Tensor(...)},
                %"val_527"<FLOAT,[768,768]>{Tensor(...)},
                %"val_565"<FLOAT,[768,768]>{Tensor(...)},
                %"val_569"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_578"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_582"<FLOAT,[768,768]>{Tensor(...)},
                %"val_590"<FLOAT,[768,768]>{Tensor(...)},
                %"val_598"<FLOAT,[768,768]>{Tensor(...)},
                %"val_636"<FLOAT,[768,768]>{Tensor(...)},
                %"val_640"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_649"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_653"<FLOAT,[768,768]>{Tensor(...)},
                %"val_661"<FLOAT,[768,768]>{Tensor(...)},
                %"val_669"<FLOAT,[768,768]>{Tensor(...)},
                %"val_707"<FLOAT,[768,768]>{Tensor(...)},
                %"val_711"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_720"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_724"<FLOAT,[768,768]>{Tensor(...)},
                %"val_732"<FLOAT,[768,768]>{Tensor(...)},
                %"val_740"<FLOAT,[768,768]>{Tensor(...)},
                %"val_778"<FLOAT,[768,768]>{Tensor(...)},
                %"val_782"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_791"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_795"<FLOAT,[768,768]>{Tensor(...)},
                %"val_803"<FLOAT,[768,768]>{Tensor(...)},
                %"val_811"<FLOAT,[768,768]>{Tensor(...)},
                %"val_849"<FLOAT,[768,768]>{Tensor(...)},
                %"val_853"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_862"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_866"<FLOAT,[768,768]>{Tensor(...)},
                %"val_874"<FLOAT,[768,768]>{Tensor(...)},
                %"val_882"<FLOAT,[768,768]>{Tensor(...)},
                %"val_920"<FLOAT,[768,768]>{Tensor(...)},
                %"val_924"<FLOAT,[768,3072]>{Tensor(...)},
                %"val_933"<FLOAT,[3072,768]>{Tensor(...)},
                %"val_10"<INT64,[1]>{Tensor<INT64,[1]>(array([1]), name='val_10')},
                %"val_39"<INT64,[1]>{Tensor<INT64,[1]>(array([2]), name='val_39')},
                %"val_937"<INT64,[2]>{Tensor<INT64,[2]>(array([1, 2]), name='val_937')},
                %"val_40"<INT64,[1]>{Tensor<INT64,[1]>(array([3]), name='val_40')},
                %"val_938"<INT64,[2]>{Tensor<INT64,[2]>(array([0, 1]), name='val_938')},
                %"val_71"<INT64,[1]>{Tensor<INT64,[1]>(array([-1]), name='val_71')},
                %"val_89"<INT64,[1]>{Tensor<INT64,[1]>(array([64]), name='val_89')},
                %"val_110"<INT64,[1]>{Tensor<INT64,[1]>(array([9223372036854775807]), name='val_110')},
                %"val_112"<INT64,[1]>{Tensor<INT64,[1]>(array([-2]), name='val_112')},
                %"val_114"<INT64,[1]>{Tensor<INT64,[1]>(array([-9223372036854775808]), name='val_114')},
                %"val_126"<FLOAT,[]>{Tensor<FLOAT,[]>(array(0., dtype=float32), name='val_126')},
                %"val_127"<FLOAT,[]>{Tensor<FLOAT,[]>(array(-3.4028235e+38, dtype=float32), name='val_127')},
                %"val_145"<FLOAT,[]>{Tensor<FLOAT,[]>(array(1.4142135, dtype=float32), name='val_145')},
                %"val_148"<FLOAT,[]>{Tensor<FLOAT,[]>(array(1., dtype=float32), name='val_148')},
                %"val_150"<FLOAT,[]>{Tensor<FLOAT,[]>(array(0.5, dtype=float32), name='val_150')}
            ),
        ) {
              0 |  # node_Shape_0
                   %"val_0"<INT64,[1]> ⬅️ ::Shape(%"input_ids") {end=1, start=0}
              1 |  # node_sym_size_int_15
                   %"sym_size_int_15"<INT64,[]> ⬅️ ::Squeeze(%"val_0")
              2 |  # node_Shape_1
                   %"val_1"<INT64,[1]> ⬅️ ::Shape(%"attention_mask") {end=2, start=1}
              3 |  # node_sym_size_int_18
                   %"sym_size_int_18"<INT64,[]> ⬅️ ::Squeeze(%"val_1")

In [ ]:
from onnxruntime.quantization import quantize_dynamic, QuantType

In [ ]:
import onnx
#from onnxruntime.quantization import quantize_dynamic, QuantType

In [ ]:
!pip install -q onnxconverter-common

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.5/89.5 kB 7.8 MB/s eta 0:00:00

In [ ]:
import onnx
from onnxconverter_common import float16

model = onnx.load('models/book-classifier.onnx')
model_fp16 = float16.convert_float_to_float16(model)
onnx.save(model_fp16, 'models/book-classifier-fp16.onnx')

# Testing of ONNX Inference

## Normal ONNX

In [ ]:
import onnxruntime as rt
from transformers import AutoTokenizer
import torch

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("roberta-base")

class_labels = list(encode_topic_types.keys())

inf_session = rt.InferenceSession('models-roberta-base/book-roberta-base-classifier.onnx')
input_name = inf_session.get_inputs()[0].name
output_name = inf_session.get_outputs()[0].name

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [ ]:
preds = []
for idx, row in tqdm(valid_df.iterrows(), total=valid_df.shape[0]):
  desc = row['description']
  input_ids = tokenizer(desc)['input_ids'][:512]

  probs = inf_session.run([output_name], {input_name: [input_ids]})[0]
  probs = torch.FloatTensor(probs)

  masks = torch.sigmoid(probs) >= 0.5
  labels = [class_labels[idx] for idx, mask in enumerate(masks[0]) if mask]

  pred_topics = [0] * len(encode_topic_types)
  for label in labels:
    pred_topics[encode_topic_types[label]] = 1
  preds.append(pred_topics)

  0%|          | 0/2135 [00:00<?, ?it/s]

In [ ]:
valid_df_processed = valid_df.copy()
valid_df_processed['topic_category'] = valid_df_processed['topic_category'].apply(ast.literal_eval)

metric_measures(valid_df_processed, preds)

F1 Score (Micro) = 0.7288135593220338
F1 Score (Macro) = 0.2692030142935526

## Quantized ONNX

In [ ]:
print(os.listdir('models'))

['book-distillBert-classifier-stage-0.pth', 'book-distillBert-classifier-stage-1.pth', 'book-MiniLM-L12-classifier-stage-0.pth', 'book-MiniLM-L12-classifier-stage-1.pth', 'book-roberta-base-classifier-stage-0.pth', 'book-roberta-base-classifier-stage-1.pth', 'book-classifier.onnx.data', 'book-classifier.onnx', 'book-classifier-fixed.onnx', 'book-classifier-fp16.onnx']

In [ ]:
#import os
print(os.listdir('models'))
print(os.listdir('models-roberta-base'))

['book-distillBert-classifier-stage-0.pth', 'book-distillBert-classifier-stage-1.pth', 'book-MiniLM-L12-classifier-stage-0.pth', 'book-MiniLM-L12-classifier-stage-1.pth', 'book-roberta-base-classifier-stage-0.pth', 'book-roberta-base-classifier-stage-1.pth', 'book-classifier.onnx.data', 'book-classifier.onnx', 'book-classifier-fixed.onnx', 'book-classifier-fp16.onnx']
['book-roberta-base-classifier-stage-0.pkl', 'book-roberta-base-classifier-stage-1.pkl', 'book-roberta-base-classifier-inferred.onnx', 'book-roberta-base-classifier.onnx.data', 'book-roberta-base-classifier.onnx']

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("roberta-base")

class_labels = list(encode_topic_types.keys())

inf_session = rt.InferenceSession('models/book-classifier.onnx')
input_name = inf_session.get_inputs()[0].name
output_name = inf_session.get_outputs()[0].name

In [ ]:
preds = []
for idx, row in tqdm(valid_df.iterrows(), total=valid_df.shape[0]):
  desc = row['description']
  encoded = tokenizer(desc, truncation=True, max_length=512, return_tensors='np')
  probs = inf_session.run(
    [output_name],
    {
        'input_ids': encoded['input_ids'],
        'attention_mask': encoded['attention_mask']
    }
)[0]
  probs = torch.FloatTensor(probs)

  masks = torch.sigmoid(probs) >= 0.5
  labels = [class_labels[idx] for idx, mask in enumerate(masks[0]) if mask]

  pred_topics = [0] * len(encode_topic_types)
  for label in labels:
    pred_topics[encode_topic_types[label]] = 1
  preds.append(pred_topics)

  0%|          | 0/2135 [00:00<?, ?it/s]

In [ ]:
valid_df_processed = valid_df.copy()
valid_df_processed['topic_category'] = valid_df_processed['topic_category'].apply(ast.literal_eval)

metric_measures(valid_df_processed, preds)

F1 Score (Micro) = 0.7288135593220338
F1 Score (Macro) = 0.2692030142935526